// Run against a local static server only; Supabase/auth are mocked before page scripts.
const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const options={headless:true};
 if(process.env.CHROMIUM_MODULE){const imported=require(process.env.CHROMIUM_MODULE);const binary=imported.default||imported;options.executablePath=process.env.CHROMIUM_EXECUTABLE || await binary.executablePath();options.args=binary.args;}
 const browser=await chromium.launch(options);
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 let fail=false,oversize=false,role='admin',failureCode='PGRST202',lastRequest;
 const rows=Array.from({length:55},(_,i)=>({id:'s'+i,project_id:'p'+i,project_number:'P'+(i+1),scoop_id:'s'+i,scoop_number:'S'+(i+1),resource_id:'resource-1',issue_codes:[],info_codes:['estimate'],name:i===0?'<img src=x onerror=alert(1)>':'Project '+(i+1),project_name:'Localization',client:'Example client',account:'European languages',pm:'Alex',status:'Ongoing',date:'2026-09-24',currency:'EUR',client_value:300,profit:237.66,margin:79.22,costs:{EUR:62.34},job_count:3,scoop_count:2,estimate_count:2,unknown_cost_count:0,currency_warning_count:0,po_warning_count:0,resource:'Resource one',service:'Translation',source_language:'English',target_language:'Bulgarian',deadline:'2026-09-24T16:00:00Z',quantity:123.456,unit:'Source words',cost_basis:'PO commitment',po_id:'po-1',po_number:'PO-100',po_version:2}));
 await page.exposeFunction('fixtureRpc',async(name,args)=>{
  if(name==='current_app_role')return {data:role,error:null};
  if(name==='current_user_access_enabled')return {data:true,error:null};
  if(fail)return {data:null,error:{code:failureCode,message:'Fixture backend failure'}};
  if(name==='tms_report_options')return {data:{api_version:59,clients:[{id:'client-1',label:'Duplicate client'},{id:'client-2',label:'Duplicate client'}],accounts:[{id:'account-1',client_id:'client-1',label:'Account A'},{id:'account-2',client_id:'client-2',label:'Account B'}],pms:[{id:'pm-1',label:'Alex'}],legacy_pms:[],resources:[{id:'resource-1',label:'Resource one'}],languages:['English','Bulgarian'],services:['Translation'],currencies:['EUR','USD'],statuses:{projects:['Assign','Ongoing','Cancelled'],margin:['Assign','Ongoing','Cancelled'],jobs:['Unassigned','Assigned','In Progress','Delivered','Revision Required','Approved','Cancelled']}},error:null};
  assert.equal(name,'tms_report');lastRequest=args;
  const matched=args.p_filters.search==='empty'?[]:rows;
  return {data:{api_version:59,issue_counts:{blocking:0,estimate:55,unknown_cost:0,po_conflict:0,currency_mismatch:0,excluded:0},groups:[],rows:matched.slice(args.p_offset,args.p_offset+args.p_limit),total_count:oversize?10001:matched.length,project_count:matched.length,warning_rows:0,summary_by_currency:matched.length?[{currency:'EUR',client_value:16500,supplier_cost:3428.7,profit:13071.3,margin:79.22,estimate_count:110,incomplete_rows:0}]:[],generated_at:'2026-09-24T12:00:00Z',date_basis:args.p_type==='jobs'?'Job deadline (UTC)':'Project date',report_type:args.p_type,filters:args.p_filters,next_offset:args.p_offset+args.p_limit<matched.length?args.p_offset+args.p_limit:null},error:null};
 });
 await page.addInitScript(()=>{window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:{user:{id:'fixture'}}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signOut:async()=>({})},rpc:(name,args)=>window.fixtureRpc(name,args)})};});
 await page.route('https://cdn.jsdelivr.net/**',route=>route.fulfill({contentType:'text/javascript',body:''}));
 await page.route('https://*.supabase.co/**',route=>route.abort());
 const base=process.env.REPORT_BASE_URL||'http://127.0.0.1:8765/tms/';
 await page.goto(base+'reports.html?type=projects');await page.getByText('1–50 of 55',{exact:true}).waitFor();
 assert.equal(await page.locator('#reportTable tbody tr').count(),50);
 assert.equal(await page.locator('#reportTable img').count(),0);
 await page.locator('#nextPage').click();await page.getByText('51–55 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_offset,50);
 await page.locator('#previousPage').click();await page.getByText('1–50 of 55',{exact:true}).waitFor();
 await page.locator('#search').fill('empty');await page.getByRole('button',{name:'View report',exact:true}).click();await page.getByText('No matching results.',{exact:false}).waitFor();assert.equal(await page.locator('#exportReport').isDisabled(),true);
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();
 const download=page.waitForEvent('download');await page.locator('#exportReport').click();assert.match((await download).suggestedFilename(),/retodo-projects.*csv/);assert.equal(lastRequest.p_limit,10000);
 oversize=true;await page.locator('#exportReport').click();await page.getByText('Export is limited to 10,000 rows.',{exact:false}).waitFor();oversize=false;
 await page.locator('.reports-main').evaluate(e=>e.scrollTop=0);await page.screenshot({path:'/tmp/reports-filters-desktop.png'});
 await page.locator('#reportTable').scrollIntoViewIfNeeded();assert.ok((await page.locator('#reportTable').boundingBox()).height>100);await page.screenshot({path:'/tmp/reports-projects-desktop.png',fullPage:true});
 await page.locator('.tabs-bar').getByText('Jobs',{exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_type,'jobs');await page.getByRole('columnheader',{name:'PO / Version',exact:true}).waitFor();
 role='qa';await page.goto(base+'reports.html?type=margin');await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(await page.locator('#exportReport').isEnabled(),true);assert.equal(await page.locator('#quality').isEnabled(),true);
 await page.locator('.nav-item').filter({hasText:'Clients'}).click();await page.locator('#sub-cli').waitFor({state:'visible'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/reports-margin-mobile.png'});await page.locator('#reportTable').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/reports-results-mobile.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 fail=true;await page.getByRole('button',{name:'View report',exact:true}).click();await page.getByText('Reports service is unavailable.',{exact:false}).waitFor();assert.equal(await page.locator('#reportTable tbody tr').count(),0);assert.equal(await page.locator('#exportReport').isDisabled(),true);
 failureCode='42501';await page.locator('#retryReport').click();await page.getByText('You do not have access',{exact:false}).waitFor();
 failureCode='TIMEOUT';await page.locator('#retryReport').click();await page.getByText('The report timed out.',{exact:false}).waitFor();
 failureCode='NETWORK';await page.locator('#retryReport').click();await page.getByText('The report could not be loaded.',{exact:false}).waitFor();
 fail=false;role='admin';await page.setViewportSize({width:1440,height:1000});await page.goto(base+'reports.html?type=projects');await page.getByText('1–50 of 55',{exact:true}).waitFor();
 await page.locator('#client_id').fill('Duplicate client [client-2]');await page.locator('#client_id').dispatchEvent('change');
 assert.equal(await page.locator('#account_idOptions option').count(),1);assert.equal(await page.locator('#account_idOptions option').first().getAttribute('value'),'Account B [account-2]');
 await page.locator('#account_id').fill('Account B [account-2]');await page.locator('#currency').selectOption('EUR');await page.locator('#sort').selectOption('profit');
 await page.getByRole('button',{name:'View report',exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_filters.client_id,'client-2');assert.equal(lastRequest.p_sort,'profit');assert.ok(page.url().includes('client_id=client-2'));
 await page.reload();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(await page.locator('#account_id').inputValue(),'Account B [account-2]');
 await page.locator('.tabs-bar').getByText('Jobs',{exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_filters.client_id,'client-2');assert.equal(lastRequest.p_sort,'name');
 await page.locator('#moreFilters summary').click();assert.equal(await page.locator('#statuses input[value="Offered"]').count(),0);await page.locator('#statuses input[value="Assigned"]').check();
 await page.getByRole('button',{name:'View report',exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.deepEqual(lastRequest.p_filters.statuses,['Assigned']);
 assert.ok(await page.locator('a[href*="&po="]').count()>0);assert.ok(await page.locator('a[href="resource.html?id=resource-1"]').count()>0);
 await page.getByRole('button',{name:'Clear filters',exact:true}).click();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_filters.client_id,undefined);
 await page.goBack();await page.getByText('1–50 of 55',{exact:true}).waitFor();assert.equal(lastRequest.p_filters.client_id,'client-2');
 fail=true;await page.locator('#retryReport').evaluate(e=>e.hidden=false);await page.locator('#retryReport').click();await page.locator('#reportDiagnostics').waitFor({state:'visible'});fail=false;
 await page.route('**/reports.js?v=059',route=>route.abort());await page.goto(base+'reports.html?type=projects');await page.getByText('Reports could not start.',{exact:false}).waitFor({timeout:20000});assert.equal(await page.locator('#retryReport').isVisible(),true);await page.unroute('**/reports.js?v=059');
 await page.goto(base+'reports.html?type=invoices');await page.getByText('Invoice reporting is not available',{exact:false}).waitFor();assert.equal(await page.locator('#reportFilters').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS browser fixture: selectors, status contract, URL refresh/back/tab state, paging, CSV/cap, PO/resource links, QA, XSS, responsive layouts, service/permission/timeout/query errors, retry and missing-script fallback');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
