const test=require('node:test'),assert=require('node:assert/strict');
const Excel=require('../tms/vendor/exceljs-4.4.0.min.js');
const {build}=require('../tms/report-workbook');
const {parseRates}=require('../netlify/functions/report-exchange-rates');
test('Typed workbook keeps decimals numeric, Unicode readable, text inert and margins blank when incomplete',async()=>{
 const data={report_type:'projects',generated_at:'2026-09-27T12:00:00Z',total_count:1,date_basis:'Project date',filters:{search:'Милан'},fx_date:'2026-09-25',fx_rates:{USD:1.1,EUR:1},rows:[{project_number:'P1',name:'S01',client:'Милан & José',client_value:24.2,costs:{EUR:9.6},profit:null,margin:null,provisional_profit:14.6,native_client_value:24.2,native_currency:'EUR',unknown_cost_count:1,job_count:2,cost_details:[{name:'TEST',native_cost:null}],notes:'=HYPERLINK("bad")'}],summary_by_currency:[{currency:'EUR',client_value:24.2,supplier_cost:9.6,profit:null,margin:null,incomplete_rows:1}]};
 const bytes=await build(data,Excel);const book=new Excel.Workbook();await book.xlsx.load(bytes);const ws=book.getWorksheet('Details'),headers=ws.getRow(1).values;const cell=h=>ws.getRow(2).getCell(headers.indexOf(h));assert.equal(cell('Client').value,'Милан & José');assert.equal(cell('Client value (EUR)').type,Excel.ValueType.Number);assert.equal(cell('Client value (EUR)').value,24.2);assert.equal(cell('Known cost (EUR)').value,9.6);assert.equal(cell('Margin').value,null);assert.ok(cell('Data quality').value.includes('TEST'));assert.equal(ws.views[0].ySplit,1);assert.ok(ws.getColumn(headers.indexOf('Client')).width>=25);assert.equal(book.worksheets.length,3);
 data.rows[0].client='=HYPERLINK("bad")';await book.xlsx.load(await build(data,Excel));assert.equal(book.getWorksheet('Details').getRow(2).getCell(headers.indexOf('Client')).type,Excel.ValueType.String);
});
const rates={USD:1.1,GBP:.9,CHF:.95,JPY:160,CAD:1.5,AUD:1.7,PLN:4.2,CZK:24,SEK:11};
const xml=(date,rs=rates)=>`<Cube time='${date}'>${Object.entries(rs).map(([c,n])=>`<Cube currency='${c}' rate='${n}'/>`).join('')}</Cube>`;
test('ECB parsing preserves dated units per EUR and rejects stale/incomplete/invalid rates',()=>{const d=new Date().toISOString().slice(0,10);assert.equal(parseRates(xml(d)).rates.USD,1.1);assert.equal(parseRates(xml(d)).rates.EUR,1);assert.throws(()=>parseRates(xml('2000-01-01')),/date range/);assert.throws(()=>parseRates(xml(d,{USD:1})),/complete/);assert.throws(()=>parseRates(xml(d,{...rates,USD:0})),/Invalid/);});
test('FX endpoint rejects unauthenticated, foreign-origin and non-company requests; authenticated refresh stores provider rates',async()=>{
 const originalFetch=global.fetch;process.env.SUPABASE_URL='https://fixture.supabase.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='fixture-not-a-secret';process.env.TMS_SITE_URL='https://fixture.invalid';let role='resource',stored=false;
 global.fetch=async(url,opts)=>{if(url.endsWith('/auth/v1/user'))return new Response(JSON.stringify({id:'fixture'}));if(url.endsWith('/current_app_role'))return new Response(JSON.stringify(role));if(url.endsWith('/current_user_access_enabled'))return new Response('true');if(url.includes('ecb.europa.eu'))return new Response(xml(new Date().toISOString().slice(0,10)));if(url.endsWith('/store_report_fx_061')){const payload=JSON.parse(opts.body);assert.equal(payload.p_rates.USD,1.1);stored=true;return new Response('null');}throw new Error('Unexpected '+url);};
 try{const {handler}=require('../netlify/functions/report-exchange-rates');assert.equal((await handler({httpMethod:'GET'})).statusCode,405);assert.equal((await handler({httpMethod:'POST',headers:{}})).statusCode,401);assert.equal((await handler({httpMethod:'POST',headers:{origin:'https://other.invalid'}})).statusCode,403);const event={httpMethod:'POST',headers:{authorization:'Bearer fixture',origin:'https://fixture.invalid'}};assert.equal((await handler(event)).statusCode,403);assert.equal(stored,false);role='admin';assert.equal((await handler(event)).statusCode,200);assert.equal(stored,true);}finally{global.fetch=originalFetch;}
});
