let projectId, project, clients = [], accounts = [], contacts = [], billingEntities = [];
let specializations = [], projectSpecializations = [], scopeLines = [], scoops = [], jobs = [];
let scoopEditorLines = [], scoopDeletedLineIds = [];
let accountSpecializationIds = [];
let resources = [], internalResources = [], issues = [], files = [], purchaseOrders = [];
let clientRateCards = [];
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const val = id => document.getElementById(id).value.trim();
const nullable = id => val(id) || null;
const toLocalDT = iso => { if(!iso)return ''; const d=new Date(iso),p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; };
const datePart = iso => toLocalDT(iso).slice(0,10);
const timePart = iso => toLocalDT(iso).slice(11,16);
const combineDateTime = (dateId,timeId) => {const date=val(dateId);return date?`${date}T${val(timeId)||'17:00'}`:null};
const localDateValue = (date=new Date()) => {const p=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}`};
function futureJobDeadline(scoop=null){const inherited=scoop?.deadline||project?.deadline,projectDeadline=inherited?new Date(inherited):null;if(projectDeadline&&projectDeadline>new Date())return {date:datePart(inherited),time:timePart(inherited)};const next=new Date(Date.now()+60*60*1000);return {date:localDateValue(next),time:`${String(next.getHours()).padStart(2,'0')}:${String(next.getMinutes()).padStart(2,'0')}`}}
function jobDeadlineIsPast(){const value=combineDateTime('j-deadline-date','j-deadline-time');return value&&new Date(value)<new Date()}
const money = (amount, currency = project?.currency || 'EUR') => `${Number(amount || 0).toFixed(2)} ${currency}`;
const unitMoney = (amount, currency = project?.currency || 'EUR') => `${Number(amount || 0).toFixed(4)} ${currency}`;
const roundMoney = amount => Math.round((Number(amount || 0) + Number.EPSILON) * 100) / 100;
function toggleSub(id,item){document.getElementById(id).classList.toggle('open');item.classList.toggle('open')}
function closeModal(id){document.getElementById(id).classList.add('hidden');document.querySelectorAll(`#${id} .error-msg`).forEach(el=>el.classList.add('hidden'))}
function showError(message){const el=document.getElementById('projectError');el.textContent=message;el.classList.remove('hidden');el.scrollIntoView({behavior:'smooth'})}
function modalError(id,message){const el=document.getElementById(id);el.textContent=message;el.classList.remove('hidden')}
function setStatus(message){const el=document.getElementById('saveStatus');el.textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>el.textContent='',3500)}
function options(rows,label,selected='',empty='Non-defined'){return `<option value="">${empty}</option>`+rows.map(row=>`<option value="${row.id}" ${row.id===selected?'selected':''}>${esc(typeof label==='function'?label(row):row[label])}</option>`).join('')}
function languageOptions(selected=''){return '<option value="">Select language…</option>'+TMS_REF.languages.map(language=>`<option value="${esc(language)}" ${language===selected?'selected':''}>${esc(language)}</option>`).join('')}
function specName(id){return specializations.find(row=>row.id===id)?.name||'—'}
function resourceName(resource){return resource.legal_name||resource.company_name||resource.internal_number}
function eligibleContacts(){return contacts.filter(contact=>contact.active!==false&&(!contact.account_id||contact.account_id===val('g-account')))}
function renderContactOptions(selectedId=''){const eligible=eligibleContacts(),selected=eligible.some(contact=>contact.id===selectedId)?selectedId:'';document.getElementById('g-contact').innerHTML=options(eligible,'full_name',selected)}
function staffOptions(selectedId,legacyText){let html='<option value="">Non-defined</option>'+internalResources.map(resource=>{const inactive=resource.lifecycle_status!=='Active';return `<option value="${resource.id}" ${resource.id===selectedId?'selected':''} ${inactive&&resource.id!==selectedId?'disabled':''}>${esc(resourceName(resource))}${inactive?` · ${esc(resource.lifecycle_status)}`:''}</option>`}).join('');if(!selectedId&&legacyText)html+=`<option value="" selected>${esc(legacyText)} · legacy text</option>`;return html}
function renderStaffLifecycleWarning(){const assignments=[['Project Manager',project.project_manager_resource_id],['QA Specialist',project.qa_specialist_resource_id],['Project Coordinator',project.project_coordinator_resource_id]];const inactive=assignments.map(([role,id])=>[role,internalResources.find(resource=>resource.id===id)]).filter(([,resource])=>resource&&resource.lifecycle_status!=='Active');const warning=document.getElementById('staffLifecycleWarning');warning.classList.toggle('hidden',!inactive.length);warning.textContent=inactive.length?`${inactive.map(([role,resource])=>`${role}: ${resourceName(resource)} (${resource.lifecycle_status})`).join(' · ')}. Historical assignment is preserved; select an Active Internal Resource to reassign.`:''}

function populateProject(){const name=project.display_name||project.project_number,languageSummary=scoops.map(scoop=>`${scoop.source_language} → ${scoop.target_language}`).join(' · ');document.title=`${name} — RetodoOps TMS`;document.getElementById('projectTitle').textContent=name;document.getElementById('projectBreadcrumb').textContent=name;document.getElementById('projectSubtitle').textContent=`${project.clients?.name||''} · ${scoops.length} Scoop${scoops.length===1?'':'s'}${languageSummary?` · ${languageSummary}`:''}`;if(project.quote_id){const link=document.getElementById('quoteLink');link.href=`quote.html?id=${project.quote_id}`;link.classList.remove('hidden')}const fields={'g-name':project.project_number,'g-date':project.project_date,'g-client-ref':project.client_reference,'g-email-ref':project.email_reference,'g-deadline-date':datePart(project.deadline),'g-deadline-time':timePart(project.deadline),'g-status':project.status,'g-wait-reason':project.waiting_reason,'g-wait-follow-date':datePart(project.waiting_follow_up_at),'g-wait-follow-time':timePart(project.waiting_follow_up_at),'g-type':project.project_type,'g-production':project.production_mode,'g-cat':project.cat_system,'g-instructions':project.client_instructions,'g-po':project.po_number,'g-delivery':project.place_of_delivery,'g-comment':project.accounting_comment,'c-price':Number(project.price||0).toFixed(2),'c-currency':project.currency,'c-price-source':project.price_source,'c-price-reason':project.price_override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('g-client').innerHTML=options(clients,'name',project.client_id,'Select Client…');document.getElementById('g-pm').innerHTML=staffOptions(project.project_manager_resource_id,project.project_manager);document.getElementById('g-qa').innerHTML=staffOptions(project.qa_specialist_resource_id,project.qa_specialist);document.getElementById('g-coordinator').innerHTML=staffOptions(project.project_coordinator_resource_id,project.project_coordinator);renderStaffLifecycleWarning();document.getElementById('g-account').innerHTML=options(accounts,'name',project.account_id);renderContactOptions(project.contact_id);document.getElementById('g-billing').innerHTML=options(billingEntities,'name',project.billing_entity_id,'Default billing entity');document.getElementById('g-missingpo').checked=!!project.missing_po;document.getElementById('g-upcoming').checked=!!project.upcoming;document.getElementById('g-urgent').checked=!!project.urgent;renderFinancialSummary();renderSpecializations();renderFinancialControls()}

async function applyClientChange(){const clientId=val('g-client');const [a,c,b,rc]=await Promise.all([_sb.from('client_accounts').select('*').eq('client_id',clientId).order('name'),_sb.from('client_contacts').select('*').eq('client_id',clientId).order('full_name'),_sb.from('client_billing_entities').select('*').eq('client_id',clientId).order('is_default',{ascending:false}),_sb.from('client_rate_cards').select('*').eq('client_id',clientId).eq('active',true).order('name')]);accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];clientRateCards=rc.data||[];accountSpecializationIds=[];document.getElementById('g-account').innerHTML=options(accounts,'name','','Non-defined');renderContactOptions('');document.getElementById('g-billing').innerHTML=options(billingEntities,'name','','Default billing entity');renderSpecializations();renderFinancialControls()}
function renderProjectFinancialMetrics(price=project?.price,expense=project?.expense,currency=val('c-currency')||project?.currency||'EUR'){
  const revenue=roundMoney(price),cost=roundMoney(expense),profit=roundMoney(revenue-cost),margin=revenue?profit/revenue*100:0,percent=`${margin.toFixed(2)}%`;
  document.getElementById('sum-price').textContent=money(revenue,currency);document.getElementById('sum-expense').textContent=money(cost,currency);document.getElementById('sum-profit').textContent=money(profit,currency);document.getElementById('sum-margin').textContent=percent;
  const footer={price:'scope-result-price',expense:'scope-result-expense',profit:'scope-result-profit',margin:'scope-result-margin'};if(document.getElementById(footer.price)){document.getElementById(footer.price).textContent=money(revenue,currency);document.getElementById(footer.expense).textContent=money(cost,currency);document.getElementById(footer.profit).textContent=money(profit,currency);document.getElementById(footer.margin).textContent=percent}
}
function renderFinancialSummary(){renderProjectFinancialMetrics();document.getElementById('sum-financial').textContent=project.financial_status||'Not Ready'}
function availableRateCards(){const accountId=val('g-account');return clientRateCards.filter(card=>card.active&&(card.account_id===null||card.account_id===accountId))}
function renderFinancialControls(){
  const price=document.getElementById('c-price'),help=document.getElementById('c-price-help');
  price.readOnly=true;help.textContent='Total of all active Scoop prices. Edit the owning Scoop to change any financial value.';
}
function renderSpecializations(){const selected=new Set(projectSpecializations.map(row=>row.specialization_id)),accountId=val('g-account'),allowed=accountId?specializations.filter(spec=>accountSpecializationIds.includes(spec.id)):specializations,container=document.getElementById('g-specializations'),menu=container.querySelector('.catalog-dropdown-menu');menu.innerHTML=allowed.map(spec=>`<label class="checkbox-row"><input type="checkbox" value="${spec.id}" ${accountId||selected.has(spec.id)?'checked':''} ${accountId?'disabled':''}>${esc(spec.name)}</label>`).join('')||'<span class="muted">No specializations configured.</span>';const update=()=>{const chosen=[...container.querySelectorAll('input:checked')].map(input=>specName(input.value));container.querySelector('summary').textContent=chosen.length?(chosen.length<=2?chosen.join(', '):`${chosen.length} specializations selected`):'Select specializations…'};menu.querySelectorAll('input').forEach(input=>input.addEventListener('change',update));update();document.getElementById('g-specializations-help').textContent=accountId?'Inherited from the selected Account. Edit the Account to change this list.':'Select one or more values from the Settings catalogue.'}
async function applyAccountDefaults(){const account=accounts.find(row=>row.id===val('g-account'));accountSpecializationIds=[];if(account){if(account.default_production_mode)document.getElementById('g-production').value=account.default_production_mode;if(account.default_cat_system)document.getElementById('g-cat').value=account.default_cat_system;if(account.instructions)document.getElementById('g-instructions').value=account.instructions;const {data}=await _sb.from('client_account_specializations').select('specialization_id').eq('account_id',account.id);accountSpecializationIds=(data||[]).map(row=>row.specialization_id)}renderContactOptions(document.getElementById('g-contact').value);renderSpecializations();renderFinancialControls()}

async function saveProject(){
  const priceSource=val('c-price-source'),waitingFollow=combineDateTime('g-wait-follow-date','g-wait-follow-time');
  if(val('g-status')==='Waiting'&&(!val('g-wait-reason')||!waitingFollow))return showError('Waiting requires a reason and follow-up date.');
  const checked=[...document.querySelectorAll('#g-specializations input:checked')].map(input=>input.value),checkedSet=new Set(checked);
  if(!checked.length)return showError('Select at least one Project specialization.');
  const used=[...jobs.map(job=>job.specialization_id),...scopeLines.filter(line=>line.service_type!=='Quote discount').map(line=>line.specialization_id)].filter(Boolean);
  if(used.some(id=>!checkedSet.has(id)))return showError('A specialization used by an existing Job or financial line cannot be removed from the Project.');
  if(!val('g-name')||!val('g-date')||!val('g-client'))return showError('Project number, date and Client are required.');
  const payload={project_date:val('g-date'),client_id:val('g-client'),account_id:nullable('g-account'),contact_id:nullable('g-contact'),billing_entity_id:nullable('g-billing'),client_reference:nullable('g-client-ref'),email_reference:nullable('g-email-ref'),deadline:combineDateTime('g-deadline-date','g-deadline-time'),status:val('g-status'),waiting_reason:nullable('g-wait-reason'),waiting_follow_up_at:waitingFollow,project_manager_resource_id:nullable('g-pm'),qa_specialist_resource_id:nullable('g-qa'),project_coordinator_resource_id:nullable('g-coordinator'),project_type:val('g-type'),production_mode:val('g-production'),cat_system:nullable('g-cat'),client_instructions:nullable('g-instructions'),po_number:nullable('g-po'),missing_po:document.getElementById('g-missingpo').checked,place_of_delivery:nullable('g-delivery'),accounting_comment:nullable('g-comment'),upcoming:document.getElementById('g-upcoming').checked,urgent:document.getElementById('g-urgent').checked,currency:val('c-currency'),price_source:priceSource||null,price_override_reason:nullable('c-price-reason')};
  const {error}=await _sb.from('projects').update(payload).eq('id',projectId);if(error)return showError(error.message);
  const pricingContextChanged=project.client_id!==payload.client_id||project.account_id!==payload.account_id;
  if(pricingContextChanged&&scopeLines.some(line=>line.client_rate_item_id)){const detached=await _sb.from('scope_items').update({client_rate_item_id:null,rate_source:'Manual',override_reason:'Client/Account changed; retained price snapshot for review'}).eq('project_id',projectId).not('client_rate_item_id','is',null);if(detached.error)return showError(`Project saved, but linked financial lines need review: ${detached.error.message}`)}
  const currentManual=projectSpecializations.filter(link=>link.source==='Manual').map(link=>link.specialization_id),toDelete=currentManual.filter(id=>!checkedSet.has(id));
  const accountChanged=project.account_id!==payload.account_id,existingAfterAccountChange=new Set(projectSpecializations.filter(link=>!accountChanged||link.source==='Manual').map(link=>link.specialization_id));
  const toInsert=payload.account_id?[]:checked.filter(id=>!existingAfterAccountChange.has(id));
  if(toDelete.length){const deletion=await _sb.from('project_specializations').delete().eq('project_id',projectId).eq('source','Manual').in('specialization_id',toDelete);if(deletion.error)return showError(`Project saved, but specializations failed: ${deletion.error.message}`)}
  if(toInsert.length){const inserted=await _sb.from('project_specializations').insert(toInsert.map(id=>({project_id:projectId,specialization_id:id,source:'Manual'})));if(inserted.error)return showError(`Project saved, but specializations failed: ${inserted.error.message}`)}
  await loadProject();setStatus('Saved ✓');
}

function scopeAmount(line,quantity=Number(line.quantity||0)){
  const amount=line.price_unit==='Fixed fee'?Number(line.unit_price||0):quantity*Number(line.unit_price||0);
  return roundMoney(['Discount','Credit'].includes(line.adjustment_type)?-Math.abs(amount):Math.abs(amount));
}
function scopeUnitOptions(selected='Source words'){return ['Source words','Target words','Hours','Pages','Minutes','Fixed fee'].map(unit=>`<option ${unit===selected?'selected':''}>${unit}</option>`).join('')}
function scopeDescription(line={}){return line.description||[line.service_type,line.cat_band].filter(Boolean).join(' · ')||''}
function renderScope(){
  const body=document.getElementById('scopeTbody'),currency=project.currency||'EUR';
  const rows=scopeLines.map(line=>{const scoop=scoops.find(item=>item.id===line.project_scoop_id),scoopLabel=scoop?.scoop_number||'Unassigned Scoop',scoopLink=scoop?`<a class="table-link" href="project.html?id=${encodeURIComponent(projectId)}&scoop=${encodeURIComponent(scoop.id)}">${esc(scoopLabel)}</a>`:esc(scoopLabel);return `<tr><td>${scoopLink}</td><td>${esc(scopeDescription(line)||'—')}</td><td class="number-cell">${Number(line.quantity||0)}</td><td>${esc(line.price_unit||'—')}</td><td class="number-cell">${unitMoney(line.unit_price,currency)}</td><td>${esc(line.rate_source||'—')}</td><td>${esc(line.adjustment_type||'—')}</td><td class="number-cell"><strong>${money(scopeAmount(line),currency)}</strong></td></tr>`}).join('');
  const empty=scopeLines.length?'':'<tr class="state-row"><td colspan="8">No detailed financial lines. Add pricing inside a Scoop.</td></tr>',total=scopeLines.reduce((sum,line)=>sum+scopeAmount(line),0);
  body.innerHTML=rows+empty+`<tr class="scope-total-row"><td colspan="7">Detailed line total</td><td class="number-cell">${money(total,currency)}</td></tr>`;renderProjectFinancialMetrics(project.price,project.expense,currency);
}
function specOptions(selected=''){return '<option value="">Select specialization…</option>'+projectSpecializations.map(link=>{const spec=specializations.find(item=>item.id===link.specialization_id);return spec?`<option value="${spec.id}" ${spec.id===selected?'selected':''}>${esc(spec.name)}</option>`:''}).join('')}
function derivedJobSpecialization(service=val('j-service')){const line=scopeLines.find(item=>item.service_type===service&&item.specialization_id);return line?.specialization_id||projectSpecializations[0]?.specialization_id||''}
function syncInheritedJobSpecialization(){const id=derivedJobSpecialization();document.getElementById('j-specialization').value=id;document.getElementById('j-specialization-display').textContent=id?specName(id):'Project specialization is missing'}
function jobSupplierCost(job){const po=purchaseOrders.filter(row=>row.job_id===job.id).find(row=>['Issued','Acknowledged'].includes(row.status));return {amount:po?Number(po.total||0):Number(job.supplier_amount||0),currency:po?.currency||job.supplier_currency||project.currency}}
function scoopMetrics(scoop){const scoopJobs=jobs.filter(job=>job.project_scoop_id===scoop.id&&!['Declined','Cancelled'].includes(job.status)),price=roundMoney(scoop.price||0),expense=roundMoney(scoopJobs.reduce((sum,job)=>sum+jobSupplierCost(job).amount,0)),profit=roundMoney(price-expense),margin=price?profit/price*100:0,status=TMS_REF.scoopStatus(scoopJobs);return {jobs:scoopJobs,price,expense,profit,margin,status}}
function renderScoopJobRow(job){const resource=resources.find(row=>row.id===job.resource_id),jobPOs=purchaseOrders.filter(row=>row.job_id===job.id),po=jobPOs.find(row=>!['Cancelled','Superseded'].includes(row.status))||jobPOs[0],cost=jobSupplierCost(job),jobHref=`job.html?id=${encodeURIComponent(job.id)}`,resourceHtml=resource?`<a class="table-link resource-name-link" href="resource.html?id=${encodeURIComponent(resource.id)}">${esc(resourceName(resource))}</a>`:'Unassigned',poHtml=po?`<a class="table-link po-link" href="${jobHref}">${esc(po.po_number)} · V${Number(po.current_version||1)}</a>`:job.resource_id&&job.po_required?'<span class="pill pill-amber">Missing</span>':'—';return `<tr><td><a class="table-link job-name-link" href="${jobHref}">${esc(job.job_number)}</a></td><td>${esc(job.service_type)}</td><td>${resourceHtml}</td><td>${job.deadline?new Date(job.deadline).toLocaleString('en-GB'):'—'}</td><td><span class="pill ${job.status==='Approved'?'pill-green':job.status==='Revision Required'?'pill-amber':['Unassigned','Assigned','In Progress'].includes(job.status)?'pill-blue':''}">${esc(job.status)}</span></td><td class="supplier-cost-cell">${job.resource_id?money(cost.amount,cost.currency):'—'}</td><td>${poHtml}</td></tr>`}
function renderScoops(){document.getElementById('scoopCount').textContent=scoops.length;const list=document.getElementById('scoopsList');if(!scoops.length){list.innerHTML='<div class="section-card empty-compact">No Scoops yet. Create the first language pair.</div>';return}list.innerHTML=scoops.map(scoop=>{const metrics=scoopMetrics(scoop),rows=metrics.jobs.length?metrics.jobs.map(renderScoopJobRow).join(''):'<tr class="state-row"><td colspan="7">No Jobs in this Scoop yet.</td></tr>',statusClass=metrics.status==='Approved'||metrics.status==='Delivered to Client'?'pill-green':metrics.status==='Ongoing'?'pill-blue':'pill-amber';return `<article id="scoop-${scoop.id}" class="section-card scoop-card" tabindex="-1"><div class="scoop-card-head"><div class="scoop-identity"><div class="scoop-number-row"><a class="scoop-number" href="project.html?id=${encodeURIComponent(projectId)}&scoop=${encodeURIComponent(scoop.id)}">${esc(scoop.scoop_number)}</a><span class="pill ${statusClass}">${esc(metrics.status)}</span></div><h3>${esc(scoop.source_language)} <span>→</span> ${esc(scoop.target_language)}</h3><p>${scoop.deadline?`Client deadline ${new Date(scoop.deadline).toLocaleString('en-GB')}`:'No Scoop deadline set'}</p></div><div class="scoop-actions"><div class="scoop-financials"><div><span>Client price</span><strong>${money(metrics.price,project.currency)}</strong></div><div><span>Supplier expense</span><strong>${money(metrics.expense,project.currency)}</strong></div><div><span>Profit</span><strong>${money(metrics.profit,project.currency)}</strong></div><div><span>Margin</span><strong>${metrics.margin.toFixed(2)}%</strong></div></div><button class="btn-secondary" type="button" onclick="openScoopModal('${scoop.id}')">Edit Scoop</button><button class="btn-primary" type="button" onclick="openJobModal('${scoop.id}')">+ Create Job</button></div></div><div class="table-card"><table class="module-table jobs-table"><thead><tr><th>Job</th><th>Service</th><th>Resource</th><th>Deadline</th><th>Status</th><th class="supplier-cost-header">Supplier cost</th><th>PO</th></tr></thead><tbody>${rows}</tbody></table></div></article>`}).join('')}
function openScoopModal(scoopId=null){const scoop=scoops.find(row=>row.id===scoopId),nextNumber=`${project.project_number}-S${String(scoops.length+1).padStart(2,'0')}`,source=scoop?.source_language||project.source_language||'English (UK)',target=scoop?.target_language||'';document.getElementById('scoopModalTitle').textContent=scoop?'Edit Scoop':'Create Scoop';document.getElementById('scp-id').value=scoop?.id||'';document.getElementById('scp-source').innerHTML=languageOptions(source);document.getElementById('scp-target').innerHTML=languageOptions(target);document.getElementById('scp-deadline-date').value=datePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-time').value=timePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-date').min=localDateValue();document.getElementById('scp-price').value=Number(scoop?.price||0).toFixed(2);document.getElementById('scp-price-currency').textContent=project.currency||'EUR';document.querySelector('#scoopNumberPreview strong').textContent=scoop?.scoop_number||nextNumber;const button=document.getElementById('saveScoopBtn');button.textContent=scoop?'Save Scoop':'Create Scoop';button.disabled=false;const error=document.getElementById('scoopError');error.textContent='';error.classList.add('hidden');document.getElementById('scoopModal').classList.remove('hidden');document.getElementById('scp-target').focus()}
async function saveScoop(){const id=val('scp-id'),source=val('scp-source'),target=val('scp-target'),price=Number(val('scp-price')||0),button=document.getElementById('saveScoopBtn'),deadline=combineDateTime('scp-deadline-date','scp-deadline-time'),existing=scoops.find(row=>row.id===id),deadlineChanged=deadline&&new Date(deadline).getTime()!==new Date(existing?.deadline||0).getTime();if(!source||!target)return modalError('scoopError','Source and Target languages are required.');if(!TMS_REF.languages.includes(source)||!TMS_REF.languages.includes(target))return modalError('scoopError','Choose Source and Target from the shared language list.');if(source===target)return modalError('scoopError','Source and Target languages must be different.');if(!Number.isFinite(price)||price<0)return modalError('scoopError','Scoop price must be zero or a positive number.');if(deadline&&new Date(deadline)<new Date()&&deadlineChanged)return modalError('scoopError','Scoop deadline cannot be in the past.');button.disabled=true;button.textContent='Saving…';const payload={source_language:source,target_language:target,deadline,price};const result=id?await _sb.rpc('update_project_scoop',{p_scoop_id:id,p_payload:payload}):await _sb.rpc('create_project_scoop',{p_project_id:projectId,p_payload:payload});if(result.error){button.disabled=false;button.textContent=id?'Save Scoop':'Create Scoop';return modalError('scoopError',result.error.message)}closeModal('scoopModal');await loadProject();setStatus(id?'Scoop updated ✓':'Scoop created ✓')}
function focusRequestedScoop(){const scoopId=new URLSearchParams(location.search).get('scoop');if(!scoopId)return;const tab=document.querySelector('.record-tab[data-tab="scoops"]'),pane=document.getElementById('pane-scoops'),card=document.getElementById(`scoop-${scoopId}`);if(!tab||!pane||!card)return;document.querySelectorAll('.record-tab').forEach(item=>item.classList.toggle('active',item===tab));document.querySelectorAll('.record-pane').forEach(item=>item.classList.toggle('active',item===pane));requestAnimationFrame(()=>{card.scrollIntoView({behavior:'smooth',block:'start'});card.focus({preventScroll:true})})}
function openJobModal(scoopId){const scoop=scoops.find(row=>row.id===scoopId);if(!scoop)return showError('Select a valid Scoop before creating a Job.');document.getElementById('jobModalTitle').textContent='Create a separate Job';document.getElementById('j-scoop-id').value=scoop.id;document.getElementById('j-scoop-context').textContent=`${scoop.scoop_number} · ${scoop.source_language} → ${scoop.target_language}`;const deadline=futureJobDeadline(scoop),fields={'j-service':project.project_type||'Translation','j-deadline-date':deadline.date,'j-deadline-time':deadline.time,'j-notes':''};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('j-deadline-date').min=localDateValue();syncInheritedJobSpecialization();document.getElementById('j-po-required').checked=true;const error=document.getElementById('jobError');error.textContent='';error.classList.add('hidden');const button=document.getElementById('createJobBtn');button.disabled=false;button.textContent='Create and open Job';document.getElementById('jobModal').classList.remove('hidden')}
async function saveJob(){if(!val('j-scoop-id'))return modalError('jobError','Select a Scoop before creating a Job.');if(!val('j-specialization'))return modalError('jobError','Add a specialization to the Project before creating a Job.');if(jobDeadlineIsPast())return modalError('jobError','Resource deadline cannot be in the past.');const button=document.getElementById('createJobBtn');if(button.disabled)return;button.disabled=true;button.textContent='Creating new Job…';const payload={project_scoop_id:val('j-scoop-id'),service_type:val('j-service'),specialization_id:val('j-specialization'),deadline:combineDateTime('j-deadline-date','j-deadline-time'),po_required:document.getElementById('j-po-required').checked,notes:nullable('j-notes')};const {data,error}=await _sb.rpc('create_project_job',{p_project_id:projectId,p_payload:payload});if(error){button.disabled=false;button.textContent='Create and open Job';return modalError('jobError',error.message)}location.href=`job.html?id=${encodeURIComponent(data)}`}

function renderIssues(){document.getElementById('issueCount').textContent=issues.length;const body=document.getElementById('issuesTbody');if(!issues.length){body.innerHTML='<tr class="state-row"><td colspan="5">No post-delivery issues.</td></tr>';return}body.innerHTML=issues.map(issue=>`<tr><td>${esc(issue.status)}</td><td>${esc(issue.severity||'—')}</td><td>${esc(issue.description)}</td><td>${new Date(issue.reported_at).toLocaleString('en-GB')}</td><td>${esc(issue.resolution||'—')}</td></tr>`).join('')}

async function loadProject(){
  const p=await _sb.from('projects').select('*, clients(name,code)').eq('id',projectId).single();
  if(p.error)return showError(p.error.message);
  project=p.data;
  const [cl,a,c,b,s,ps,sc,sp,j,po,fl,staff,as,rc]=await Promise.all([
    _sb.from('clients').select('id,name,code,restriction_status').order('name'),
    _sb.from('client_accounts').select('*').eq('client_id',project.client_id).order('name'),
    _sb.from('client_contacts').select('*').eq('client_id',project.client_id).order('full_name'),
    _sb.from('client_billing_entities').select('*').eq('client_id',project.client_id).order('is_default',{ascending:false}),
    _sb.from('specializations').select('*').eq('active',true).order('name'),
    _sb.from('project_specializations').select('*').eq('project_id',projectId).order('created_at'),
    _sb.from('scope_items').select('*').eq('project_id',projectId).order('sort_order'),
    _sb.from('project_scoops').select('*').eq('project_id',projectId).eq('active',true).order('created_at'),
    _sb.from('project_jobs').select('*').eq('project_id',projectId).order('created_at'),
    _sb.from('supplier_purchase_orders').select('*').eq('project_id',projectId).order('created_at',{ascending:false}),
    _sb.from('file_records').select('id').eq('project_id',projectId),
    _sb.from('resources').select('id,internal_number,legal_name,company_name,lifecycle_status,assignment_approved').eq('resource_type','Internal').order('legal_name'),
    project.account_id?_sb.from('client_account_specializations').select('specialization_id').eq('account_id',project.account_id):Promise.resolve({data:[]}),
    _sb.from('client_rate_cards').select('*').eq('client_id',project.client_id).eq('active',true).order('name')
  ]);
  clients=cl.data||[];accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];specializations=s.data||[];projectSpecializations=ps.data||[];scopeLines=sc.data||[];scoops=sp.data||[];jobs=j.data||[];purchaseOrders=po.data||[];files=fl.data||[];internalResources=staff.data||[];accountSpecializationIds=(as.data||[]).map(row=>row.specialization_id);clientRateCards=rc.data||[];
  const jobIds=jobs.map(job=>job.id),resourceIds=[...new Set(jobs.map(job=>job.resource_id).filter(Boolean))];
  if(jobIds.length){const issueResult=await _sb.from('job_issues').select('*').in('job_id',jobIds).order('reported_at',{ascending:false});issues=issueResult.data||[]}else issues=[];
  if(resourceIds.length){const resourceResult=await _sb.from('resources').select('id,internal_number,legal_name,company_name,classification,lifecycle_status').in('id',resourceIds);resources=resourceResult.data||[]}else resources=[];
  document.getElementById('fileCount').textContent=files.length;populateProject();renderScope();renderScoops();renderIssues();focusRequestedScoop();window.TMS_QUICK_NAV?.recordVisit('Project',project.id,project.display_name||project.project_number,[project.project_number,project.clients?.name,project.status].filter(Boolean).join(' · '));
}

document.querySelectorAll('.record-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.record-pane').forEach(pane=>pane.classList.toggle('active',pane.id===`pane-${tab.dataset.tab}`))}));document.getElementById('g-client').addEventListener('change',applyClientChange);document.getElementById('g-account').addEventListener('change',applyAccountDefaults);document.getElementById('c-price').addEventListener('input',()=>renderProjectFinancialMetrics(Number(val('c-price')||0),project?.expense));document.getElementById('c-currency').addEventListener('change',renderFinancialSummary);document.getElementById('g-po').addEventListener('input',event=>{if(event.target.value.trim())document.getElementById('g-missingpo').checked=false});document.getElementById('j-service').addEventListener('change',syncInheritedJobSpecialization);
(async()=>{const user=await requireAuth();if(!user)return;await Promise.all([TMS_REF.loadLanguages(_sb),TMS_REF.loadServices(_sb)]);TMS_REF.installDatalists();TMS_REF.populateServiceSelect('g-type');TMS_REF.populateServiceSelect('sc-service',{includeQuoteDiscount:true});TMS_REF.populateServiceSelect('j-service');TMS_REF.populateServiceSelect('scp-fin-service');projectId=new URLSearchParams(location.search).get('id');if(!projectId){location.href='dashboard.html';return}await loadProject()})();

function scoopLineAmount(line){const raw=line.price_unit==='Fixed fee'?Number(line.unit_price||0):Number(line.quantity||0)*Number(line.unit_price||0);return roundMoney(['Discount','Credit'].includes(line.adjustment_type)?-Math.abs(raw):Math.abs(raw))}
function scoopFinancialRow(line,index){const linked=!!line.client_rate_item_id;return `<tr data-index="${index}"><td><input class="scp-line-description" value="${esc(line.description||'')}" ${linked?'disabled':''}></td><td><input class="scp-line-quantity" type="number" min="0" step="0.001" value="${Number(line.quantity||0)}"></td><td><select class="scp-line-unit" ${linked?'disabled':''}>${scopeUnitOptions(line.price_unit||'Source words')}</select></td><td><input class="scp-line-rate" type="number" min="0" step="0.0001" value="${Number(line.unit_price||0)}" ${linked?'disabled':''}></td><td><span class="pill ${linked?'pill-blue':''}">${esc(line.rate_source||'Manual')}</span>${linked?'<small class="customer-sub">Rate-card snapshot</small>':`<input class="scp-line-reason" value="${esc(line.override_reason||'')}" placeholder="Reason required">`}</td><td class="scp-line-amount number-cell">${money(scoopLineAmount(line),project.currency)}</td><td><button type="button" class="del-line-btn" aria-label="Remove line" onclick="removeScoopFinancialLine(${index})">×</button></td></tr>`}
function renderScoopFinancialLines(){const body=document.getElementById('scp-fin-lines');body.innerHTML=scoopEditorLines.length?scoopEditorLines.map(scoopFinancialRow).join(''):'<tr class="state-row"><td colspan="7">No detailed lines. Enter a Scoop client price or load a Client rate card.</td></tr>';body.querySelectorAll('input,select').forEach(control=>control.addEventListener('input',syncScoopFinancialEditor));syncScoopFinancialEditor()}
function syncScoopFinancialEditor(){document.querySelectorAll('#scp-fin-lines tr[data-index]').forEach(row=>{const line=scoopEditorLines[Number(row.dataset.index)];line.description=row.querySelector('.scp-line-description').value;line.quantity=Number(row.querySelector('.scp-line-quantity').value||0);line.price_unit=row.querySelector('.scp-line-unit').value;line.unit_price=Number(row.querySelector('.scp-line-rate').value||0);if(!line.client_rate_item_id)line.override_reason=row.querySelector('.scp-line-reason').value;row.querySelector('.scp-line-amount').textContent=money(scoopLineAmount(line),project.currency)});const total=roundMoney(scoopEditorLines.reduce((sum,line)=>sum+scoopLineAmount(line),0)),price=document.getElementById('scp-price');if(scoopEditorLines.length){price.value=total.toFixed(2);price.readOnly=true}else price.readOnly=false;document.getElementById('scp-fin-total').textContent=money(total,project.currency)}
function removeScoopFinancialLine(index){const line=scoopEditorLines[index];if(line?.id)scoopDeletedLineIds.push(line.id);scoopEditorLines.splice(index,1);renderScoopFinancialLines()}
function addScoopFinancialLine(){scoopEditorLines.push({description:'',service_type:val('scp-fin-service')||project.project_type||'Other',specialization_id:val('scp-fin-specialization')||projectSpecializations[0]?.specialization_id||null,quantity:0,price_unit:val('scp-fin-unit')||'Source words',unit_price:0,rate_source:'Manual',override_reason:'',sort_order:(scoopEditorLines.length+1)*10});renderScoopFinancialLines();document.querySelector('#scp-fin-lines tr:last-child .scp-line-description')?.focus()}
function scoopRateMatches(item,source,target,service,specialization,unit){const sources=item.source_languages?.length?item.source_languages:(item.source_language?[item.source_language]:[]),targets=item.target_languages?.length?item.target_languages:(item.target_language?[item.target_language]:[]);return !item.base_rate_id&&item.active!==false&&item.service_type===service&&item.unit===unit&&(!item.specialization_id||item.specialization_id===specialization)&&(!sources.length||sources.includes(source))&&(!targets.length||targets.includes(target))}
async function loadScoopRateCardLines(){const cardId=val('scp-fin-card'),source=val('scp-source'),target=val('scp-target'),service=val('scp-fin-service'),specialization=val('scp-fin-specialization'),unit=val('scp-fin-unit');if(!cardId)return modalError('scoopError','Select a Client rate card.');if(!source||!target)return modalError('scoopError','Select the Scoop language pair first.');if(!specialization)return modalError('scoopError','Select a specialization.');if(scoopEditorLines.length&&!confirm('Replace the current detailed Scoop financial lines?'))return;const {data,error}=await _sb.from('client_rate_items').select('*').eq('rate_card_id',cardId).eq('active',true);if(error)return modalError('scoopError',error.message);const base=(data||[]).filter(item=>scoopRateMatches(item,source,target,service,specialization,unit)).sort((a,b)=>Number(!!b.specialization_id)-Number(!!a.specialization_id))[0];if(!base)return modalError('scoopError','No active rate-card row matches this Scoop language pair, service, specialization and unit.');const children=(data||[]).filter(item=>item.base_rate_id===base.id),card=clientRateCards.find(item=>item.id===cardId),rows=[base,...children];scoopDeletedLineIds.push(...scoopEditorLines.filter(line=>line.id).map(line=>line.id));scoopEditorLines=rows.map((item,index)=>({description:`${service} · ${item.cat_band||(children.length?'New words':unit)}`,service_type:service,specialization_id:specialization,cat_band:item.cat_band||(children.length?'New words':null),quantity:0,price_unit:item.unit,unit_price:Number(item.rate||0),rate_source:card?.account_id?'Account':'Client',override_reason:null,client_rate_item_id:item.id,sort_order:(index+1)*10}));renderScoopFinancialLines()}
function scoopRateCardOptions(selected=''){const cards=availableRateCards();return '<option value="">Select a Client rate card…</option>'+cards.map(card=>`<option value="${card.id}" ${card.id===selected?'selected':''}>${esc(card.name)} · ${esc(card.currency)}</option>`).join('')}
function openScoopModal(scoopId=null){const scoop=scoops.find(row=>row.id===scoopId),nextNumber=`${project.project_number}-S${String(scoops.length+1).padStart(2,'0')}`,source=scoop?.source_language||project.source_language||'English (UK)',target=scoop?.target_language||'',existingLines=scopeLines.filter(line=>line.project_scoop_id===scoopId);document.getElementById('scoopModalTitle').textContent=scoop?'Edit Scoop':'Create Scoop';document.getElementById('scp-id').value=scoop?.id||'';document.getElementById('scp-source').innerHTML=languageOptions(source);document.getElementById('scp-target').innerHTML=languageOptions(target);document.getElementById('scp-deadline-date').value=datePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-time').value=timePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-date').min=localDateValue();document.getElementById('scp-price').value=Number(scoop?.price||0).toFixed(2);document.getElementById('scp-price-currency').textContent=project.currency||'EUR';document.querySelector('#scoopNumberPreview strong').textContent=scoop?.scoop_number||nextNumber;document.getElementById('scp-fin-card').innerHTML=scoopRateCardOptions();TMS_REF.populateServiceSelect('scp-fin-service',{selected:existingLines[0]?.service_type||project.project_type||'Translation'});document.getElementById('scp-fin-specialization').innerHTML=specOptions(existingLines[0]?.specialization_id||projectSpecializations[0]?.specialization_id||'');document.getElementById('scp-fin-unit').value=existingLines[0]?.price_unit||'Source words';scoopEditorLines=existingLines.map(line=>({...line}));scoopDeletedLineIds=[];renderScoopFinancialLines();const button=document.getElementById('saveScoopBtn');button.textContent=scoop?'Save Scoop':'Create Scoop';button.disabled=false;const error=document.getElementById('scoopError');error.textContent='';error.classList.add('hidden');document.getElementById('scoopModal').classList.remove('hidden');document.getElementById('scp-target').focus()}
async function saveScoop(){syncScoopFinancialEditor();const id=val('scp-id'),source=val('scp-source'),target=val('scp-target'),price=Number(val('scp-price')||0),button=document.getElementById('saveScoopBtn'),deadline=combineDateTime('scp-deadline-date','scp-deadline-time'),existing=scoops.find(row=>row.id===id),deadlineChanged=deadline&&new Date(deadline).getTime()!==new Date(existing?.deadline||0).getTime();if(!source||!target)return modalError('scoopError','Source and Target languages are required.');if(!TMS_REF.languages.includes(source)||!TMS_REF.languages.includes(target))return modalError('scoopError','Choose Source and Target from the Settings language catalogue.');if(source===target)return modalError('scoopError','Source and Target languages must be different.');if(!Number.isFinite(price)||price<0)return modalError('scoopError','Scoop price must be zero or a positive number.');if(deadline&&new Date(deadline)<new Date()&&deadlineChanged)return modalError('scoopError','Scoop deadline cannot be in the past.');for(const line of scoopEditorLines){if(!line.description.trim())return modalError('scoopError','Every detailed financial line requires a description.');if(!line.specialization_id)return modalError('scoopError','Every detailed financial line requires a specialization.');if(!line.client_rate_item_id&&!line.override_reason?.trim())return modalError('scoopError',`Add a reason for “${line.description}”.`)}button.disabled=true;button.textContent='Saving…';const payload={source_language:source,target_language:target,deadline,price},result=id?await _sb.rpc('update_project_scoop',{p_scoop_id:id,p_payload:payload}):await _sb.rpc('create_project_scoop',{p_project_id:projectId,p_payload:payload});if(result.error){button.disabled=false;button.textContent=id?'Save Scoop':'Create Scoop';return modalError('scoopError',result.error.message)}const savedScoopId=id||result.data,financial=await _sb.rpc('save_scoop_financial_lines',{p_scoop_id:savedScoopId,p_lines:scoopEditorLines,p_deleted_ids:[...new Set(scoopDeletedLineIds)],p_fallback_price:price});if(financial.error){button.disabled=false;button.textContent=id?'Save Scoop':'Create Scoop';return modalError('scoopError',`Scoop saved, but its financials failed: ${financial.error.message}`)}closeModal('scoopModal');await loadProject();setStatus(id?'Scoop and financials updated ✓':'Scoop and financials created ✓')}

// Update 033: Client-rate selection determines the Unit. The matching context
// is language pair + service + specialization; Unit is supplied by the matched
// rate-card row and displayed inside the detailed financial table.
function updateProjectFinancialTotals(){
  const rows=[...document.querySelectorAll('.project-price-row')];let detailedTotal=0;
  const rowAmounts=new Map();
  rows.forEach(row=>{
    const quantity=Number(row.querySelector('.scope-quantity').value||0),unitPrice=Number(row.querySelector('.scope-unit-price').value||0),unit=row.querySelector('.scope-unit').value,adjustment=row.querySelector('.scope-adjustment').value;
    const raw=unit==='Fixed fee'?unitPrice:quantity*unitPrice,amount=roundMoney(['Discount','Credit'].includes(adjustment)?-Math.abs(raw):Math.abs(raw));
    row.querySelector('.scope-amount').value=amount.toFixed(2);detailedTotal+=amount;
    const line=scopeLines.find(item=>item.id===row.dataset.id),scoopId=line?.project_scoop_id||scoops[0]?.id;
    if(scoopId)rowAmounts.set(scoopId,(rowAmounts.get(scoopId)||0)+amount);
  });
  const previewTotal=roundMoney(scoops.reduce((sum,scoop)=>sum+(rowAmounts.has(scoop.id)?rowAmounts.get(scoop.id):Number(scoop.price||0)),0));
  const currency=val('c-currency')||project?.currency||'EUR';
  document.getElementById('c-price').value=previewTotal.toFixed(2);renderProjectFinancialMetrics(previewTotal,project?.expense,currency);
}
function addScoopFinancialLine(){const defaultUnit=scoopEditorLines[0]?.price_unit||'Source words';scoopEditorLines.push({description:'',service_type:val('scp-fin-service')||project.project_type||'Other',specialization_id:val('scp-fin-specialization')||projectSpecializations[0]?.specialization_id||null,quantity:0,price_unit:defaultUnit,unit_price:0,rate_source:'Manual',override_reason:'',sort_order:(scoopEditorLines.length+1)*10});renderScoopFinancialLines();document.querySelector('#scp-fin-lines tr:last-child .scp-line-description')?.focus()}
function scoopRateMatches(item,source,target,service,specialization){const sources=item.source_languages?.length?item.source_languages:(item.source_language?[item.source_language]:[]),targets=item.target_languages?.length?item.target_languages:(item.target_language?[item.target_language]:[]);return !item.base_rate_id&&item.active!==false&&item.service_type===service&&(!item.specialization_id||item.specialization_id===specialization)&&(!sources.length||sources.includes(source))&&(!targets.length||targets.includes(target))}
async function loadScoopRateCardLines(){const cardId=val('scp-fin-card'),source=val('scp-source'),target=val('scp-target'),service=val('scp-fin-service'),specialization=val('scp-fin-specialization');if(!cardId)return modalError('scoopError','Select a Client rate card.');if(!source||!target)return modalError('scoopError','Select the Scoop language pair first.');if(!specialization)return modalError('scoopError','Select a specialization.');if(scoopEditorLines.length&&!confirm('Replace the current detailed Scoop financial lines?'))return;const {data,error}=await _sb.from('client_rate_items').select('*').eq('rate_card_id',cardId).eq('active',true);if(error)return modalError('scoopError',error.message);const matches=(data||[]).filter(item=>scoopRateMatches(item,source,target,service,specialization)).sort((a,b)=>Number(!!b.specialization_id)-Number(!!a.specialization_id)||new Date(b.updated_at||0)-new Date(a.updated_at||0)),base=matches[0];if(!base)return modalError('scoopError','No active rate-card row matches this Scoop language pair, service and specialization.');const children=(data||[]).filter(item=>item.base_rate_id===base.id),card=clientRateCards.find(item=>item.id===cardId),rows=[base,...children];scoopDeletedLineIds.push(...scoopEditorLines.filter(line=>line.id).map(line=>line.id));scoopEditorLines=rows.map((item,index)=>({description:`${service} · ${item.cat_band||(children.length?'New words':item.unit)}`,service_type:service,specialization_id:specialization,cat_band:item.cat_band||(children.length?'New words':null),quantity:0,price_unit:item.unit,unit_price:Number(item.rate||0),rate_source:card?.account_id?'Account':'Client',override_reason:null,client_rate_item_id:item.id,sort_order:(index+1)*10}));renderScoopFinancialLines()}
function openScoopModal(scoopId=null){const scoop=scoops.find(row=>row.id===scoopId),nextNumber=`${project.project_number}-S${String(scoops.length+1).padStart(2,'0')}`,source=scoop?.source_language||project.source_language||'English (UK)',target=scoop?.target_language||'',existingLines=scopeLines.filter(line=>line.project_scoop_id===scoopId);document.getElementById('scoopModalTitle').textContent=scoop?'Edit Scoop':'Create Scoop';document.getElementById('scp-id').value=scoop?.id||'';document.getElementById('scp-source').innerHTML=languageOptions(source);document.getElementById('scp-target').innerHTML=languageOptions(target);document.getElementById('scp-deadline-date').value=datePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-time').value=timePart(scoop?.deadline||project.deadline);document.getElementById('scp-deadline-date').min=localDateValue();document.getElementById('scp-price').value=Number(scoop?.price||0).toFixed(2);document.getElementById('scp-price-currency').textContent=project.currency||'EUR';document.querySelector('#scoopNumberPreview strong').textContent=scoop?.scoop_number||nextNumber;document.getElementById('scp-fin-card').innerHTML=scoopRateCardOptions();TMS_REF.populateServiceSelect('scp-fin-service',{selected:existingLines[0]?.service_type||project.project_type||'Translation'});document.getElementById('scp-fin-specialization').innerHTML=specOptions(existingLines[0]?.specialization_id||projectSpecializations[0]?.specialization_id||'');scoopEditorLines=existingLines.map(line=>({...line}));scoopDeletedLineIds=[];renderScoopFinancialLines();const button=document.getElementById('saveScoopBtn');button.textContent=scoop?'Save Scoop':'Create Scoop';button.disabled=false;const error=document.getElementById('scoopError');error.textContent='';error.classList.add('hidden');document.getElementById('scoopModal').classList.remove('hidden');document.getElementById('scp-target').focus()}
document.getElementById('scp-fin-unit')?.closest('.field')?.remove();
