let projectId, project, accounts = [], contacts = [], billingEntities = [];
let specializations = [], projectSpecializations = [], scopeLines = [], jobs = [];
let accountSpecializationIds = [];
let resources = [], internalResources = [], issues = [], files = [], purchaseOrders = [];
let clientRateCards = [];
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const val = id => document.getElementById(id).value.trim();
const nullable = id => val(id) || null;
const toLocalDT = iso => { if(!iso)return ''; const d=new Date(iso),p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; };
const datePart = iso => toLocalDT(iso).slice(0,10);
const timePart = iso => toLocalDT(iso).slice(11,16);
const combineDateTime = (dateId,timeId) => {const date=val(dateId);return date?`${date}T${val(timeId)||'17:00'}`:null};
const money = (amount, currency = project?.currency || 'EUR') => `${Number(amount || 0).toFixed(2)} ${currency}`;
function toggleSub(id,item){document.getElementById(id).classList.toggle('open');item.classList.toggle('open')}
function closeModal(id){document.getElementById(id).classList.add('hidden');document.querySelectorAll(`#${id} .error-msg`).forEach(el=>el.classList.add('hidden'))}
function showError(message){const el=document.getElementById('projectError');el.textContent=message;el.classList.remove('hidden');el.scrollIntoView({behavior:'smooth'})}
function modalError(id,message){const el=document.getElementById(id);el.textContent=message;el.classList.remove('hidden')}
function setStatus(message){const el=document.getElementById('saveStatus');el.textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>el.textContent='',3500)}
function options(rows,label,selected='',empty='Non-defined'){return `<option value="">${empty}</option>`+rows.map(row=>`<option value="${row.id}" ${row.id===selected?'selected':''}>${esc(typeof label==='function'?label(row):row[label])}</option>`).join('')}
function specName(id){return specializations.find(row=>row.id===id)?.name||'—'}
function resourceName(resource){return resource.legal_name||resource.company_name||resource.internal_number}
function eligibleContacts(){return contacts.filter(contact=>contact.active!==false&&(!contact.account_id||contact.account_id===val('g-account')))}
function renderContactOptions(selectedId=''){const eligible=eligibleContacts(),selected=eligible.some(contact=>contact.id===selectedId)?selectedId:'';document.getElementById('g-contact').innerHTML=options(eligible,'full_name',selected)}
function staffOptions(selectedId,legacyText){let html='<option value="">Non-defined</option>'+internalResources.map(resource=>{const inactive=resource.lifecycle_status!=='Active';return `<option value="${resource.id}" ${resource.id===selectedId?'selected':''} ${inactive&&resource.id!==selectedId?'disabled':''}>${esc(resourceName(resource))}${inactive?` · ${esc(resource.lifecycle_status)}`:''}</option>`}).join('');if(!selectedId&&legacyText)html+=`<option value="" selected>${esc(legacyText)} · legacy text</option>`;return html}
function renderStaffLifecycleWarning(){const assignments=[['Project Manager',project.project_manager_resource_id],['QA Specialist',project.qa_specialist_resource_id],['Project Coordinator',project.project_coordinator_resource_id]];const inactive=assignments.map(([role,id])=>[role,internalResources.find(resource=>resource.id===id)]).filter(([,resource])=>resource&&resource.lifecycle_status!=='Active');const warning=document.getElementById('staffLifecycleWarning');warning.classList.toggle('hidden',!inactive.length);warning.textContent=inactive.length?`${inactive.map(([role,resource])=>`${role}: ${resourceName(resource)} (${resource.lifecycle_status})`).join(' · ')}. Historical assignment is preserved; select an Active Internal Resource to reassign.`:''}

function populateProject(){const name=project.display_name||project.project_number;document.title=`${name} — RetodoOps TMS`;document.getElementById('projectTitle').textContent=name;document.getElementById('projectBreadcrumb').textContent=name;document.getElementById('projectSubtitle').textContent=`${project.clients?.name||''} · ${project.source_language||'—'} → ${project.target_language||'—'}`;if(project.quote_id){const link=document.getElementById('quoteLink');link.href=`quote.html?id=${project.quote_id}`;link.classList.remove('hidden')}const fields={'g-name':name,'g-date':project.project_date,'g-client':project.clients?.name,'g-client-ref':project.client_reference,'g-email-ref':project.email_reference,'g-source':project.source_language,'g-target':project.target_language,'g-deadline-date':datePart(project.deadline),'g-deadline-time':timePart(project.deadline),'g-status':project.status,'g-wait-reason':project.waiting_reason,'g-wait-follow-date':datePart(project.waiting_follow_up_at),'g-wait-follow-time':timePart(project.waiting_follow_up_at),'g-type':project.project_type,'g-production':project.production_mode,'g-cat':project.cat_system,'g-instructions':project.client_instructions,'g-po':project.po_number,'g-delivery':project.place_of_delivery,'g-comment':project.accounting_comment,'c-price':project.price,'c-currency':project.currency,'c-price-source':project.price_source,'c-price-reason':project.price_override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('g-pm').innerHTML=staffOptions(project.project_manager_resource_id,project.project_manager);document.getElementById('g-qa').innerHTML=staffOptions(project.qa_specialist_resource_id,project.qa_specialist);document.getElementById('g-coordinator').innerHTML=staffOptions(project.project_coordinator_resource_id,project.project_coordinator);renderStaffLifecycleWarning();document.getElementById('g-account').innerHTML=options(accounts,'name',project.account_id);renderContactOptions(project.contact_id);document.getElementById('g-billing').innerHTML=options(billingEntities,'name',project.billing_entity_id,'Default billing entity');document.getElementById('g-missingpo').checked=!!project.missing_po;document.getElementById('g-upcoming').checked=!!project.upcoming;document.getElementById('g-urgent').checked=!!project.urgent;renderFinancialSummary();renderSpecializations();renderFinancialControls()}
function renderFinancialSummary(){document.getElementById('sum-price').textContent=money(project.price);document.getElementById('sum-expense').textContent=money(project.expense);document.getElementById('sum-margin').textContent=money(project.margin_amount);document.getElementById('sum-margin-pct').textContent=`${Number(project.scoop_margin||0).toFixed(2)}%`;document.getElementById('sum-financial').textContent=project.financial_status||'Not Ready'}
function availableRateCards(){const accountId=val('g-account');return clientRateCards.filter(card=>card.active&&(card.account_id===null||card.account_id===accountId))}
function renderFinancialControls(){
  const detailed=scopeLines.length>0,price=document.getElementById('c-price'),help=document.getElementById('c-price-help');
  price.readOnly=detailed;help.textContent=detailed?'Calculated automatically from the financial lines below. Delete all lines to return to a fixed Project price.':'Enter a fixed price, or load detailed price lines below.';
  const cards=availableRateCards(),cardSelect=document.getElementById('cat-rate-card'),selected=cards.some(card=>card.id===cardSelect.value)?cardSelect.value:'';
  cardSelect.innerHTML='<option value="">Select a Client rate card…</option>'+cards.map(card=>{const account=accounts.find(row=>row.id===card.account_id);return `<option value="${card.id}" ${card.id===selected?'selected':''}>${esc(card.name)} · ${esc(account?.name||'Client-wide')} · ${esc(card.currency)}</option>`}).join('');
  const accountDirty=val('g-account')!==(project.account_id||'');
  document.getElementById('loadRateGridBtn').disabled=!cards.length||accountDirty;
  document.getElementById('loadBlankGridBtn').disabled=accountDirty;
  const gridError=document.getElementById('catGridError');
  if(accountDirty){gridError.textContent='Save the Account change before loading a price grid.';gridError.classList.remove('hidden')}else if(gridError.textContent==='Save the Account change before loading a price grid.'){gridError.classList.add('hidden');gridError.textContent=''}
  const specializationId=projectSpecializations[0]?.specialization_id;
  document.getElementById('cat-grid-context').textContent=`${project.project_type||'Translation'} · ${specName(specializationId)} · ${project.source_language||'Any source'} → ${project.target_language||'Any target'}`;
}
async function loadCatGrid(blank){
  const rateCardId=val('cat-rate-card'),service=project.project_type||'Translation',specializationId=projectSpecializations[0]?.specialization_id||null,unit=val('cat-unit');
  const errorEl=document.getElementById('catGridError');errorEl.classList.add('hidden');
  if(!blank&&!rateCardId){errorEl.textContent='Select a Client rate card first.';errorEl.classList.remove('hidden');return}
  if(!specializationId){errorEl.textContent='Save a Project specialization before loading the CAT grid.';errorEl.classList.remove('hidden');return}
  const bands=new Set(['New words','50–74%','75–84%','85–94%','95–99%','100%','Repetitions']);
  const replacing=scopeLines.some(line=>line.service_type===service&&line.specialization_id===specializationId&&line.price_unit===unit&&bands.has(line.cat_band));
  if(replacing&&!window.confirm('Replace the existing standard CAT rows for this Project context and unit?'))return;
  const {error}=await _sb.rpc('replace_project_cat_grid',{p_project_id:projectId,p_rate_card_id:blank?null:rateCardId,p_service_type:service,p_specialization_id:specializationId,p_unit:unit});
  if(error){errorEl.textContent=error.message;errorEl.classList.remove('hidden');return}
  await loadProject();setStatus(blank?'Blank CAT grid loaded ✓':'Client rate card loaded ✓');
}
function renderSpecializations(){const selected=new Set(projectSpecializations.map(row=>row.specialization_id)),accountId=val('g-account');const allowed=accountId?specializations.filter(spec=>accountSpecializationIds.includes(spec.id)):specializations;document.getElementById('g-specializations').innerHTML=allowed.map(spec=>`<label class="checkbox-row"><input type="checkbox" value="${spec.id}" ${accountId||selected.has(spec.id)?'checked':''} ${accountId?'disabled':''}>${esc(spec.name)}</label>`).join('')||'<span class="muted">No specializations configured.</span>';document.getElementById('g-specializations-help').textContent=accountId?'Inherited from the selected Account. Edit the Account to change this list.':'No Account selected: choose at least one specialization.'}
async function applyAccountDefaults(){const account=accounts.find(row=>row.id===val('g-account'));accountSpecializationIds=[];if(account){if(account.default_production_mode)document.getElementById('g-production').value=account.default_production_mode;if(account.default_cat_system)document.getElementById('g-cat').value=account.default_cat_system;if(account.instructions)document.getElementById('g-instructions').value=account.instructions;const {data}=await _sb.from('client_account_specializations').select('specialization_id').eq('account_id',account.id);accountSpecializationIds=(data||[]).map(row=>row.specialization_id)}renderContactOptions(document.getElementById('g-contact').value);renderSpecializations();renderFinancialControls()}

async function saveProject(){
  const priceSource=val('c-price-source'),waitingFollow=combineDateTime('g-wait-follow-date','g-wait-follow-time');
  if(['Manual','Fixed'].includes(priceSource)&&!val('c-price-reason'))return showError('A manual or fixed Client price requires an explanation.');
  if(val('g-status')==='Waiting'&&(!val('g-wait-reason')||!waitingFollow))return showError('Waiting requires a reason and follow-up date.');
  const checked=[...document.querySelectorAll('#g-specializations input:checked')].map(input=>input.value),checkedSet=new Set(checked);
  if(!checked.length)return showError('Select at least one Project specialization.');
  const used=[...jobs.map(job=>job.specialization_id),...scopeLines.filter(line=>line.service_type!=='Quote discount').map(line=>line.specialization_id)].filter(Boolean);
  if(used.some(id=>!checkedSet.has(id)))return showError('A specialization used by an existing Job or financial line cannot be removed from the Project.');
  const payload={account_id:nullable('g-account'),contact_id:nullable('g-contact'),billing_entity_id:nullable('g-billing'),client_reference:nullable('g-client-ref'),email_reference:nullable('g-email-ref'),deadline:combineDateTime('g-deadline-date','g-deadline-time'),status:val('g-status'),waiting_reason:nullable('g-wait-reason'),waiting_follow_up_at:waitingFollow,project_manager_resource_id:nullable('g-pm'),qa_specialist_resource_id:nullable('g-qa'),project_coordinator_resource_id:nullable('g-coordinator'),project_type:val('g-type'),production_mode:val('g-production'),cat_system:nullable('g-cat'),client_instructions:nullable('g-instructions'),po_number:nullable('g-po'),missing_po:document.getElementById('g-missingpo').checked,place_of_delivery:nullable('g-delivery'),accounting_comment:nullable('g-comment'),upcoming:document.getElementById('g-upcoming').checked,urgent:document.getElementById('g-urgent').checked,price:scopeLines.length?Number(project.price||0):Number(val('c-price')||0),currency:val('c-currency'),price_source:priceSource||null,price_override_reason:nullable('c-price-reason')};
  const {error}=await _sb.from('projects').update(payload).eq('id',projectId);if(error)return showError(error.message);
  const currentManual=projectSpecializations.filter(link=>link.source==='Manual').map(link=>link.specialization_id),toDelete=currentManual.filter(id=>!checkedSet.has(id));
  const accountChanged=project.account_id!==payload.account_id,existingAfterAccountChange=new Set(projectSpecializations.filter(link=>!accountChanged||link.source==='Manual').map(link=>link.specialization_id));
  const toInsert=payload.account_id?[]:checked.filter(id=>!existingAfterAccountChange.has(id));
  if(toDelete.length){const deletion=await _sb.from('project_specializations').delete().eq('project_id',projectId).eq('source','Manual').in('specialization_id',toDelete);if(deletion.error)return showError(`Project saved, but specializations failed: ${deletion.error.message}`)}
  if(toInsert.length){const inserted=await _sb.from('project_specializations').insert(toInsert.map(id=>({project_id:projectId,specialization_id:id,source:'Manual'})));if(inserted.error)return showError(`Project saved, but specializations failed: ${inserted.error.message}`)}
  await loadProject();setStatus('Saved ✓');
}

function renderScope(){const body=document.getElementById('scopeTbody');if(!scopeLines.length){body.innerHTML='<tr class="state-row"><td colspan="6">No financial lines. Enter a fixed Project price or load a CAT grid.</td></tr>';return}body.innerHTML=scopeLines.map(line=>`<tr class="clickable-row" data-id="${line.id}"><td>${esc(line.cat_band||line.service_type||'—')}</td><td class="number-cell">${line.quantity??0}</td><td>${esc(line.price_unit||'—')}</td><td class="number-cell">${money(line.unit_price)}</td><td class="number-cell">${money(line.price)}</td><td>${esc(line.rate_source||'—')}${line.client_rate_item_id?'<div class="customer-sub">Linked rate-card row</div>':''}</td></tr>`).join('');body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>openScopeModal(row.dataset.id)))}
function specOptions(selected=''){return '<option value="">Select specialization…</option>'+projectSpecializations.map(link=>{const spec=specializations.find(item=>item.id===link.specialization_id);return spec?`<option value="${spec.id}" ${spec.id===selected?'selected':''}>${esc(spec.name)}</option>`:''}).join('')}
function openScopeModal(lineId=null){const line=scopeLines.find(row=>row.id===lineId),linked=!!line?.client_rate_item_id;document.getElementById('scopeModalTitle').textContent=line?'Edit financial line':'Add financial line';const fields={'sc-id':line?.id,'sc-rate-id':line?.client_rate_item_id,'sc-service':line?.service_type||project.project_type||'Translation','sc-quantity':line?.quantity??0,'sc-unit':line?.price_unit||'Source words','sc-band':line?.cat_band,'sc-unit-price':line?.unit_price??0,'sc-amount':line?.price??0,'sc-source':line?.rate_source||'Manual','sc-reason':line?.override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('sc-specialization').innerHTML=specOptions(line?.specialization_id||'');['sc-service','sc-specialization','sc-unit','sc-band','sc-unit-price','sc-source'].forEach(id=>document.getElementById(id).disabled=linked);document.getElementById('deleteScopeBtn').classList.toggle('hidden',!line);document.getElementById('scopeModal').classList.remove('hidden')}
function calculateScope(){const q=Number(val('sc-quantity')||0),rate=Number(val('sc-unit-price')||0);document.getElementById('sc-amount').value=(val('sc-unit')==='Fixed fee'?rate:q*rate).toFixed(2)}
async function saveScopeLine(){const id=val('sc-id'),source=val('sc-source'),rateId=nullable('sc-rate-id');if(val('sc-service')!=='Quote discount'&&!val('sc-specialization'))return modalError('scopeError','Specialization is required.');if(['Account','Client'].includes(source)&&!rateId)return modalError('scopeError','Select Manual as the source and explain the zero/missing price, or reload a matching Client rate-card row.');if(['Manual','Fixed'].includes(source)&&!val('sc-reason'))return modalError('scopeError','A manual/fixed line requires an explanation.');const payload={project_id:projectId,service_type:val('sc-service'),specialization_id:nullable('sc-specialization'),quantity:Number(val('sc-quantity')||0),price_unit:val('sc-unit'),cat_band:nullable('sc-band'),unit_price:Number(val('sc-unit-price')||0),price:Number(val('sc-amount')||0),rate_source:source,override_reason:nullable('sc-reason'),client_rate_item_id:rateId};const {error}=id?await _sb.from('scope_items').update(payload).eq('id',id):await _sb.from('scope_items').insert(payload);if(error)return modalError('scopeError',error.message);closeModal('scopeModal');await loadProject();setStatus('Financial line saved ✓')}
async function deleteScopeLine(){const id=val('sc-id');if(!id||!window.confirm('Delete this financial line?'))return;const {error}=await _sb.from('scope_items').delete().eq('id',id);if(error)return modalError('scopeError',error.message);closeModal('scopeModal');await loadProject();setStatus('Financial line deleted ✓')}

function renderJobs(){document.getElementById('jobCount').textContent=jobs.length;const body=document.getElementById('jobsTbody');if(!jobs.length){body.innerHTML='<tr class="state-row"><td colspan="7">No Jobs yet.</td></tr>';return}body.innerHTML=jobs.map(job=>{const resource=resources.find(row=>row.id===job.resource_id),po=purchaseOrders.find(row=>row.job_id===job.id);return `<tr class="clickable-row" data-id="${job.id}"><td><span class="code-badge">${esc(job.job_number)}</span></td><td>${esc(resource?resourceName(resource):'Unassigned')}</td><td>${esc(job.service_type)}</td><td>${job.deadline?new Date(job.deadline).toLocaleString('en-GB'):'—'}</td><td><span class="pill ${job.status==='Approved'?'pill-green':job.status==='Revision Required'?'pill-amber':job.status==='Unassigned'?'pill-blue':''}">${esc(job.status)}</span></td><td class="number-cell">${job.resource_id?money(job.supplier_amount,job.supplier_currency):'—'}</td><td>${po?esc(po.po_number):job.resource_id&&job.po_required?'<span class="pill pill-amber">Missing</span>':'—'}</td></tr>`}).join('');body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>location.href=`job.html?id=${encodeURIComponent(row.dataset.id)}`))}
function openJobModal(){document.getElementById('jobModalTitle').textContent='Create Job';const fields={'j-id':'','j-service':project.project_type||'Translation','j-deadline-date':datePart(project.deadline),'j-deadline-time':timePart(project.deadline),'j-quantity':'','j-unit':'Source words','j-notes':''};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('j-specialization').innerHTML=specOptions(projectSpecializations[0]?.specialization_id||'');document.getElementById('j-po-required').checked=true;document.getElementById('jobModal').classList.remove('hidden')}
async function saveJob(){if(!val('j-specialization'))return modalError('jobError','Job specialization is required.');const payload={project_id:projectId,resource_id:null,service_type:val('j-service'),source_language:project.source_language,target_language:project.target_language,specialization_id:val('j-specialization'),status:'Unassigned',deadline:combineDateTime('j-deadline-date','j-deadline-time'),quantity:val('j-quantity')===''?null:Number(val('j-quantity')),unit:val('j-unit'),supplier_rate:null,supplier_currency:project.currency||'EUR',supplier_amount:0,po_required:document.getElementById('j-po-required').checked,notes:nullable('j-notes'),created_by:(await _sb.auth.getUser()).data.user?.id||null};const {data,error}=await _sb.from('project_jobs').insert(payload).select('id').single();if(error)return modalError('jobError',error.message);location.href=`job.html?id=${encodeURIComponent(data.id)}`}

function renderIssues(){document.getElementById('issueCount').textContent=issues.length;const body=document.getElementById('issuesTbody');if(!issues.length){body.innerHTML='<tr class="state-row"><td colspan="5">No post-delivery issues.</td></tr>';return}body.innerHTML=issues.map(issue=>`<tr><td>${esc(issue.status)}</td><td>${esc(issue.severity||'—')}</td><td>${esc(issue.description)}</td><td>${new Date(issue.reported_at).toLocaleString('en-GB')}</td><td>${esc(issue.resolution||'—')}</td></tr>`).join('')}

async function loadProject(){
  const p=await _sb.from('projects').select('*, clients(name,code)').eq('id',projectId).single();
  if(p.error)return showError(p.error.message);
  project=p.data;
  const [a,c,b,s,ps,sc,j,po,fl,staff,as,rc]=await Promise.all([
    _sb.from('client_accounts').select('*').eq('client_id',project.client_id).order('name'),
    _sb.from('client_contacts').select('*').eq('client_id',project.client_id).order('full_name'),
    _sb.from('client_billing_entities').select('*').eq('client_id',project.client_id).order('is_default',{ascending:false}),
    _sb.from('specializations').select('*').eq('active',true).order('name'),
    _sb.from('project_specializations').select('*').eq('project_id',projectId),
    _sb.from('scope_items').select('*').eq('project_id',projectId).order('sort_order'),
    _sb.from('project_jobs').select('*').eq('project_id',projectId).order('created_at'),
    _sb.from('supplier_purchase_orders').select('*').eq('project_id',projectId),
    _sb.from('file_records').select('id').eq('project_id',projectId),
    _sb.from('resources').select('id,internal_number,legal_name,company_name,lifecycle_status,assignment_approved').eq('resource_type','Internal').order('legal_name'),
    project.account_id?_sb.from('client_account_specializations').select('specialization_id').eq('account_id',project.account_id):Promise.resolve({data:[]}),
    _sb.from('client_rate_cards').select('*').eq('client_id',project.client_id).eq('active',true).order('name')
  ]);
  accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];specializations=s.data||[];projectSpecializations=ps.data||[];scopeLines=sc.data||[];jobs=j.data||[];purchaseOrders=po.data||[];files=fl.data||[];internalResources=staff.data||[];accountSpecializationIds=(as.data||[]).map(row=>row.specialization_id);clientRateCards=rc.data||[];
  const jobIds=jobs.map(job=>job.id),resourceIds=[...new Set(jobs.map(job=>job.resource_id).filter(Boolean))];
  if(jobIds.length){const issueResult=await _sb.from('job_issues').select('*').in('job_id',jobIds).order('reported_at',{ascending:false});issues=issueResult.data||[]}else issues=[];
  if(resourceIds.length){const resourceResult=await _sb.from('resources').select('id,internal_number,legal_name,company_name,classification,lifecycle_status').in('id',resourceIds);resources=resourceResult.data||[]}else resources=[];
  document.getElementById('fileCount').textContent=files.length;populateProject();renderScope();renderJobs();renderIssues();
}

document.querySelectorAll('.record-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.record-pane').forEach(pane=>pane.classList.toggle('active',pane.id===`pane-${tab.dataset.tab}`))}));document.getElementById('g-account').addEventListener('change',applyAccountDefaults);['sc-quantity','sc-unit-price','sc-unit'].forEach(id=>document.getElementById(id).addEventListener('input',calculateScope));document.getElementById('g-po').addEventListener('input',event=>{if(event.target.value.trim())document.getElementById('g-missingpo').checked=false});
(async()=>{const user=await requireAuth();if(!user)return;projectId=new URLSearchParams(location.search).get('id');if(!projectId){location.href='dashboard.html';return}await loadProject()})();
