let projectId, project, accounts = [], contacts = [], billingEntities = [];
let specializations = [], projectSpecializations = [], scopeLines = [], jobs = [];
let resources = [], issues = [], files = [], purchaseOrders = [];
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const val = id => document.getElementById(id).value.trim();
const nullable = id => val(id) || null;
const toLocalDT = iso => { if(!iso)return ''; const d=new Date(iso),p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`; };
const money = (amount, currency = project?.currency || 'EUR') => `${Number(amount || 0).toFixed(2)} ${currency}`;
function toggleSub(id,item){document.getElementById(id).classList.toggle('open');item.classList.toggle('open')}
function closeModal(id){document.getElementById(id).classList.add('hidden');document.querySelectorAll(`#${id} .error-msg`).forEach(el=>el.classList.add('hidden'))}
function showError(message){const el=document.getElementById('projectError');el.textContent=message;el.classList.remove('hidden');el.scrollIntoView({behavior:'smooth'})}
function modalError(id,message){const el=document.getElementById(id);el.textContent=message;el.classList.remove('hidden')}
function setStatus(message){const el=document.getElementById('saveStatus');el.textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>el.textContent='',3500)}
function options(rows,label,selected='',empty='Non-defined'){return `<option value="">${empty}</option>`+rows.map(row=>`<option value="${row.id}" ${row.id===selected?'selected':''}>${esc(typeof label==='function'?label(row):row[label])}</option>`).join('')}
function specName(id){return specializations.find(row=>row.id===id)?.name||'—'}
function resourceName(resource){return resource.legal_name||resource.company_name||resource.internal_number}

function populateProject(){const name=project.display_name||project.project_number;document.title=`${name} — RetodoOps TMS`;document.getElementById('projectTitle').textContent=name;document.getElementById('projectBreadcrumb').textContent=name;document.getElementById('projectSubtitle').textContent=`${project.clients?.name||''} · ${project.source_language||'—'} → ${project.target_language||'—'}`;if(project.quote_id){const link=document.getElementById('quoteLink');link.href=`quote.html?id=${project.quote_id}`;link.classList.remove('hidden')}const fields={'g-name':name,'g-date':project.project_date,'g-client':project.clients?.name,'g-client-ref':project.client_reference,'g-email-ref':project.email_reference,'g-source':project.source_language,'g-target':project.target_language,'g-deadline':toLocalDT(project.deadline),'g-status':project.status,'g-wait-reason':project.waiting_reason,'g-wait-follow':toLocalDT(project.waiting_follow_up_at),'g-pm':project.project_manager,'g-qa':project.qa_specialist,'g-coordinator':project.project_coordinator,'g-type':project.project_type,'g-production':project.production_mode,'g-cat':project.cat_system,'g-instructions':project.client_instructions,'g-po':project.po_number,'g-delivery':project.place_of_delivery,'g-comment':project.accounting_comment,'c-price':project.price,'c-currency':project.currency,'c-price-source':project.price_source,'c-price-reason':project.price_override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('g-account').innerHTML=options(accounts,'name',project.account_id);document.getElementById('g-contact').innerHTML=options(contacts,'full_name',project.contact_id);document.getElementById('g-billing').innerHTML=options(billingEntities,'name',project.billing_entity_id,'Default billing entity');document.getElementById('g-missingpo').checked=!!project.missing_po;document.getElementById('g-upcoming').checked=!!project.upcoming;document.getElementById('g-urgent').checked=!!project.urgent;renderFinancialSummary();renderSpecializations()}
function renderFinancialSummary(){document.getElementById('sum-price').textContent=money(project.price);document.getElementById('sum-expense').textContent=money(project.expense);document.getElementById('sum-margin').textContent=money(project.margin_amount);document.getElementById('sum-margin-pct').textContent=`${Number(project.scoop_margin||0).toFixed(2)}%`;document.getElementById('sum-financial').textContent=project.financial_status||'Not Ready'}
function renderSpecializations(){const selected=new Set(projectSpecializations.map(row=>row.specialization_id));document.getElementById('g-specializations').innerHTML=specializations.map(spec=>`<label class="checkbox-row"><input type="checkbox" value="${spec.id}" ${selected.has(spec.id)?'checked':''}>${esc(spec.name)}</label>`).join('')||'<span class="muted">No specializations configured.</span>'}
async function applyAccountDefaults(){const account=accounts.find(row=>row.id===val('g-account'));if(account){if(account.default_production_mode)document.getElementById('g-production').value=account.default_production_mode;if(account.default_cat_system)document.getElementById('g-cat').value=account.default_cat_system;if(account.instructions)document.getElementById('g-instructions').value=account.instructions}const manualIds=new Set(projectSpecializations.filter(row=>row.source==='Manual').map(row=>row.specialization_id));let defaultIds=new Set();if(account){const {data}=await _sb.from('client_account_specializations').select('specialization_id').eq('account_id',account.id).eq('is_default',true);defaultIds=new Set((data||[]).map(row=>row.specialization_id))}document.querySelectorAll('#g-specializations input').forEach(input=>{input.checked=manualIds.has(input.value)||defaultIds.has(input.value)})}

async function saveProject(){const priceSource=val('c-price-source');if(['Manual','Fixed'].includes(priceSource)&&!val('c-price-reason'))return showError('A manual or fixed Client price requires an explanation.');if(val('g-status')==='Waiting'&&(!val('g-wait-reason')||!val('g-wait-follow')))return showError('Waiting requires a reason and follow-up date.');const payload={account_id:nullable('g-account'),contact_id:nullable('g-contact'),billing_entity_id:nullable('g-billing'),client_reference:nullable('g-client-ref'),email_reference:nullable('g-email-ref'),deadline:val('g-deadline')||null,status:val('g-status'),waiting_reason:nullable('g-wait-reason'),waiting_follow_up_at:val('g-wait-follow')||null,project_manager:nullable('g-pm'),qa_specialist:nullable('g-qa'),project_coordinator:nullable('g-coordinator'),project_type:val('g-type'),production_mode:val('g-production'),cat_system:nullable('g-cat'),client_instructions:nullable('g-instructions'),po_number:nullable('g-po'),missing_po:document.getElementById('g-missingpo').checked,place_of_delivery:nullable('g-delivery'),accounting_comment:nullable('g-comment'),upcoming:document.getElementById('g-upcoming').checked,urgent:document.getElementById('g-urgent').checked,price:Number(val('c-price')||0),currency:val('c-currency'),price_source:priceSource||null,price_override_reason:nullable('c-price-reason')};const checked=[...document.querySelectorAll('#g-specializations input:checked')].map(input=>input.value);const {error}=await _sb.from('projects').update(payload).eq('id',projectId);if(error)return showError(error.message);let defaultIds=new Set();if(payload.account_id){const {data}=await _sb.from('client_account_specializations').select('specialization_id').eq('account_id',payload.account_id).eq('is_default',true);defaultIds=new Set((data||[]).map(row=>row.specialization_id))}const deletion=await _sb.from('project_specializations').delete().eq('project_id',projectId).eq('source','Manual');if(deletion.error)return showError(`Project saved, but specializations failed: ${deletion.error.message}`);const manual=checked.filter(id=>!defaultIds.has(id));if(manual.length){const inserted=await _sb.from('project_specializations').insert(manual.map(id=>({project_id:projectId,specialization_id:id,source:'Manual'})));if(inserted.error)return showError(`Project saved, but specializations failed: ${inserted.error.message}`)}await loadProject();setStatus('Saved ✓')}

function renderScope(){const body=document.getElementById('scopeTbody');if(!scopeLines.length){body.innerHTML='<tr class="state-row"><td colspan="7">No commercial lines.</td></tr>';return}body.innerHTML=scopeLines.map(line=>`<tr class="clickable-row" data-id="${line.id}"><td>${esc(line.service_type||'—')}</td><td>${esc(specName(line.specialization_id))}</td><td class="number-cell">${line.quantity??'—'}</td><td>${esc(line.price_unit||'—')}${line.cat_band?`<div class="customer-sub">${esc(line.cat_band)}</div>`:''}</td><td class="number-cell">${money(line.unit_price)}</td><td class="number-cell">${money(line.price)}</td><td>${esc(line.rate_source||'—')}</td></tr>`).join('');body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>openScopeModal(row.dataset.id)))}
function specOptions(selected=''){return '<option value="">Non-defined</option>'+specializations.map(spec=>`<option value="${spec.id}" ${spec.id===selected?'selected':''}>${esc(spec.name)}</option>`).join('')}
function openScopeModal(lineId=null){const line=scopeLines.find(row=>row.id===lineId);document.getElementById('scopeModalTitle').textContent=line?'Edit commercial line':'Add commercial line';const fields={'sc-id':line?.id,'sc-service':line?.service_type||project.project_type||'Translation','sc-quantity':line?.quantity,'sc-unit':line?.price_unit||'Source words','sc-band':line?.cat_band,'sc-unit-price':line?.unit_price,'sc-amount':line?.price,'sc-source':line?.rate_source||'Manual','sc-reason':line?.override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('sc-specialization').innerHTML=specOptions(line?.specialization_id||'');document.getElementById('scopeModal').classList.remove('hidden')}
function calculateScope(){const q=Number(val('sc-quantity')||0),rate=Number(val('sc-unit-price')||0);if(q||val('sc-unit')==='Fixed fee')document.getElementById('sc-amount').value=(val('sc-unit')==='Fixed fee'?rate:q*rate).toFixed(2)}
async function saveScopeLine(){const id=val('sc-id'),source=val('sc-source');if(['Manual','Fixed'].includes(source)&&!val('sc-reason'))return modalError('scopeError','A manual/fixed line requires an explanation.');const payload={project_id:projectId,service_type:val('sc-service'),specialization_id:nullable('sc-specialization'),quantity:val('sc-quantity')===''?null:Number(val('sc-quantity')),price_unit:val('sc-unit'),cat_band:nullable('sc-band'),unit_price:val('sc-unit-price')===''?null:Number(val('sc-unit-price')),price:val('sc-amount')===''?0:Number(val('sc-amount')),rate_source:source,override_reason:nullable('sc-reason')};const {error}=id?await _sb.from('scope_items').update(payload).eq('id',id):await _sb.from('scope_items').insert(payload);if(error)return modalError('scopeError',error.message);closeModal('scopeModal');await loadProject();setStatus('Commercial line saved ✓')}

function renderJobs(){document.getElementById('jobCount').textContent=jobs.length;const body=document.getElementById('jobsTbody');if(!jobs.length){body.innerHTML='<tr class="state-row"><td colspan="7">No Jobs yet.</td></tr>';return}body.innerHTML=jobs.map(job=>{const resource=resources.find(row=>row.id===job.resource_id),po=purchaseOrders.find(row=>row.job_id===job.id);return `<tr class="clickable-row" data-id="${job.id}"><td><span class="code-badge">${esc(job.job_number)}</span></td><td>${esc(resource?resourceName(resource):'Unassigned')}</td><td>${esc(job.service_type)}</td><td>${job.deadline?new Date(job.deadline).toLocaleString('en-GB'):'—'}</td><td><span class="pill ${job.status==='Approved'?'pill-green':job.status==='Revision Required'?'pill-amber':job.status==='Unassigned'?'pill-blue':''}">${esc(job.status)}</span></td><td class="number-cell">${job.resource_id?money(job.supplier_amount,job.supplier_currency):'—'}</td><td>${po?esc(po.po_number):job.resource_id&&job.po_required?'<span class="pill pill-amber">Missing</span>':'—'}</td></tr>`}).join('');body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>location.href=`job.html?id=${encodeURIComponent(row.dataset.id)}`))}
function openJobModal(){document.getElementById('jobModalTitle').textContent='Create Job';const fields={'j-id':'','j-service':project.project_type||'Translation','j-deadline':toLocalDT(project.deadline),'j-quantity':'','j-unit':'Source words','j-notes':''};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('j-specialization').innerHTML=specOptions(projectSpecializations[0]?.specialization_id||'');document.getElementById('j-po-required').checked=true;document.getElementById('jobModal').classList.remove('hidden')}
async function saveJob(){const payload={project_id:projectId,resource_id:null,service_type:val('j-service'),source_language:project.source_language,target_language:project.target_language,specialization_id:nullable('j-specialization'),status:'Unassigned',deadline:val('j-deadline')||null,quantity:val('j-quantity')===''?null:Number(val('j-quantity')),unit:val('j-unit'),supplier_rate:null,supplier_currency:project.currency||'EUR',supplier_amount:0,po_required:document.getElementById('j-po-required').checked,notes:nullable('j-notes'),created_by:(await _sb.auth.getUser()).data.user?.id||null};const {data,error}=await _sb.from('project_jobs').insert(payload).select('id').single();if(error)return modalError('jobError',error.message);location.href=`job.html?id=${encodeURIComponent(data.id)}`}

function renderIssues(){document.getElementById('issueCount').textContent=issues.length;const body=document.getElementById('issuesTbody');if(!issues.length){body.innerHTML='<tr class="state-row"><td colspan="5">No post-delivery issues.</td></tr>';return}body.innerHTML=issues.map(issue=>`<tr><td>${esc(issue.status)}</td><td>${esc(issue.severity||'—')}</td><td>${esc(issue.description)}</td><td>${new Date(issue.reported_at).toLocaleString('en-GB')}</td><td>${esc(issue.resolution||'—')}</td></tr>`).join('')}

async function loadProject(){const p=await _sb.from('projects').select('*, clients(name,code)').eq('id',projectId).single();if(p.error)return showError(p.error.message);project=p.data;const [a,c,b,s,ps,sc,j,po,fl]=await Promise.all([_sb.from('client_accounts').select('*').eq('client_id',project.client_id).order('name'),_sb.from('client_contacts').select('*').eq('client_id',project.client_id).order('full_name'),_sb.from('client_billing_entities').select('*').eq('client_id',project.client_id).order('is_default',{ascending:false}),_sb.from('specializations').select('*').eq('active',true).order('name'),_sb.from('project_specializations').select('*').eq('project_id',projectId),_sb.from('scope_items').select('*').eq('project_id',projectId).order('sort_order'),_sb.from('project_jobs').select('*').eq('project_id',projectId).order('created_at'),_sb.from('supplier_purchase_orders').select('*').eq('project_id',projectId),_sb.from('file_records').select('id').eq('project_id',projectId)]);accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];specializations=s.data||[];projectSpecializations=ps.data||[];scopeLines=sc.data||[];jobs=j.data||[];purchaseOrders=po.data||[];files=fl.data||[];const jobIds=jobs.map(job=>job.id),resourceIds=[...new Set(jobs.map(job=>job.resource_id).filter(Boolean))];if(jobIds.length){const issueResult=await _sb.from('job_issues').select('*').in('job_id',jobIds).order('reported_at',{ascending:false});issues=issueResult.data||[]}else issues=[];if(resourceIds.length){const resourceResult=await _sb.from('resources').select('id,internal_number,legal_name,company_name,classification').in('id',resourceIds);resources=resourceResult.data||[]}else resources=[];document.getElementById('fileCount').textContent=files.length;populateProject();renderScope();renderJobs();renderIssues()}

document.querySelectorAll('.record-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.record-pane').forEach(pane=>pane.classList.toggle('active',pane.id===`pane-${tab.dataset.tab}`))}));document.getElementById('g-account').addEventListener('change',applyAccountDefaults);['sc-quantity','sc-unit-price','sc-unit'].forEach(id=>document.getElementById(id).addEventListener('input',calculateScope));document.getElementById('g-po').addEventListener('input',event=>{if(event.target.value.trim())document.getElementById('g-missingpo').checked=false});
(async()=>{const user=await requireAuth();if(!user)return;projectId=new URLSearchParams(location.search).get('id');if(!projectId){location.href='dashboard.html';return}await loadProject()})();
