/* Update 063: admin Sales navigation; Update 062: server-side company search, including exact Scoop identifiers. */
(function(){
 const KEY='retodo.quickRecent.v2',esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let active=-1,request=0,timer;
 const recent=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]').slice(0,8)}catch{return []}};
 const safeHref=h=>/^(project|job|client|resource|invoice)\.html\?/.test(h||'')?h:'#';
 function recordVisit(type,id,label,meta='',href){if(!id||!label)return;const row={kind:type,id,label,meta,href:safeHref(href||(type==='Project'?`project.html?id=${encodeURIComponent(id)}`:`job.html?id=${encodeURIComponent(id)}`))};try{localStorage.setItem(KEY,JSON.stringify([row,...recent().filter(r=>r.id!==id||r.kind!==type)].slice(0,8)))}catch{}}
 function show(rows,caption){const box=document.getElementById('quickNavResults');active=-1;box.innerHTML=`<div class="quick-nav-caption">${esc(caption)}</div>`+(rows.length?rows.map((r,i)=>`<a class="quick-nav-result" data-index="${i}" href="${esc(safeHref(r.href))}"><span class="quick-nav-kind">${esc(r.kind)}</span><span class="quick-nav-copy"><strong>${esc(r.label)}</strong><small>${esc(r.meta)}</small></span></a>`).join(''):'<div class="quick-nav-empty">No matching records.</div>');box.classList.remove('hidden');box.querySelectorAll('a').forEach((a,i)=>a.onclick=()=>recordVisit(rows[i].kind,rows[i].id,rows[i].label,rows[i].meta,rows[i].href));}
 async function search(){const rid=++request,q=document.getElementById('quickNavInput').value.trim();if(q.length<2){show(recent(),q?'Enter at least two characters':'Recently visited');return;}show([],'Searching…');try{const {data,error}=await _sb.rpc('tms_search_062',{p_query:q,p_limit:30});if(rid!==request)return;if(error)throw error;show(data||[],`Search results${data?.length===30?' · first 30; refine your search':''}`);}catch(e){if(rid!==request)return;show([],e.code==='PGRST202'?'Search needs Update 062 migration 056':e.message||'Search failed. Retry.');}}
 function navigation(){const nav=document.querySelector('.sidebar .nav');if(!nav||nav.querySelector('a[href^="invoice.html"]'))return;const section=document.createElement('div');section.innerHTML='<div class="nav-item" role="button" tabindex="0" aria-expanded="false">Invoice <span class="nav-arrow">▾</span></div><div class="nav-sub"><a href="invoice.html?type=client">Client Invoice</a><a href="invoice.html?type=linguist">Linguist Invoice</a></div>';const toggle=()=>{const open=section.lastElementChild.classList.toggle('open');section.firstElementChild.setAttribute('aria-expanded',String(open));};section.firstElementChild.onclick=toggle;section.firstElementChild.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}};const divider=nav.querySelector('.nav-divider');if(divider)divider.before(section);else nav.append(section);}
 async function install(){if(document.getElementById('quickNav')||typeof _sb==='undefined')return;try{if(!['admin','pm','qa','client_relations'].includes(await currentAppRole()))return;}catch{return;}navigation();if(await currentAppRole()==='admin'){const nav=document.querySelector('.sidebar .nav');if(nav&&!nav.querySelector('a[href="sales.html"]')){const link=document.createElement('a');link.className='nav-item'+(location.pathname.endsWith('/sales.html')?' active':'');link.href='sales.html';link.textContent='Sales';const divider=nav.querySelector('.nav-divider');if(divider)divider.before(link);else nav.append(link);}}const host=document.querySelector('.main');if(!host)return;host.insertAdjacentHTML('afterbegin','<div id="quickNav" class="quick-nav"><div class="quick-nav-shell"><span class="quick-nav-icon" aria-hidden="true">⌕</span><input id="quickNavInput" type="search" autocomplete="off" placeholder="Search Scoops, Projects, Jobs, Clients, Resources, Invoices…" aria-label="Search all modules"><kbd>/</kbd></div><div id="quickNavResults" class="quick-nav-results hidden" aria-live="polite"></div></div>');const input=document.getElementById('quickNavInput'),box=document.getElementById('quickNavResults');input.onfocus=search;input.oninput=()=>{++request;clearTimeout(timer);timer=setTimeout(search,180);};input.onkeydown=e=>{const rows=[...box.querySelectorAll('a')];if(['ArrowDown','ArrowUp'].includes(e.key)&&rows.length){e.preventDefault();active=(active+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length;rows.forEach((r,i)=>r.classList.toggle('active',i===active));rows[active].scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&active>=0){e.preventDefault();rows[active]?.click();}else if(e.key==='Escape'){++request;box.classList.add('hidden');input.blur();}};document.addEventListener('click',e=>{if(!e.target.closest('#quickNav')){++request;box.classList.add('hidden');}});document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)&&!document.activeElement?.isContentEditable){e.preventDefault();input.focus();}});}
 window.TMS_QUICK_NAV={recordVisit};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
