let quotes = [], clients = [], accounts = [], contacts = [], billingEntities = [], quoteItems = [];
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const byId = (rows, id) => rows.find(row => row.id === id);
function toggleSub(id,item){document.getElementById(id).classList.toggle('open');item.classList.toggle('open')}
function dateOnly(value){return value ? new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)) : '—'}
function money(amount,currency){return `${Number(amount||0).toFixed(2)} ${currency||'EUR'}`}
function statusPill(status){const color=status==='Accepted'?'pill-green':status==='Awaiting Client'?'pill-blue':['Declined','Cancelled','Expired'].includes(status)?'pill-red':status==='Revision Requested'?'pill-amber':'';return `<span class="pill ${color}">${esc(status)}</span>`}
function renderQuotes(){const query=document.getElementById('quoteSearch').value.trim().toLowerCase(),status=document.getElementById('quoteStatus').value;const rows=quotes.filter(q=>(!status||q.status===status)&&(!query||`${q.quote_number} ${q.title||''} ${q.client_reference||''} ${q.clients?.name||''} ${q.client_accounts?.name||''}`.toLowerCase().includes(query)));document.getElementById('quoteCount').textContent=`${rows.length} quote${rows.length===1?'':'s'}`;const body=document.getElementById('quotesTbody');if(!rows.length){body.innerHTML='<tr class="state-row"><td colspan="9">No matching quotes.</td></tr>';return}body.innerHTML=rows.map(q=>{const targets=[...new Set(quoteItems.filter(i=>i.quote_id===q.id).map(i=>i.target_language))];return `<tr class="clickable-row" data-id="${q.id}"><td><a class="proj-num" href="quote.html?id=${q.id}">${esc(q.quote_number)}</a><div class="customer-sub">${esc(q.title||'')}</div></td><td>${esc(q.clients?.name||'—')}</td><td>${esc(q.client_accounts?.name||'Non-defined')}</td><td>${esc(q.client_reference||'NOREF')}</td><td>${targets.length?targets.map(t=>`<span class="tag">${esc(t)}</span>`).join(' '):'—'}</td><td>${statusPill(q.status)}</td><td>${dateOnly(q.valid_until)}</td><td class="number-cell">${money(q.total,q.currency)}</td><td>${dateOnly(q.created_at)}</td></tr>`}).join('');body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',e=>{if(!e.target.closest('a'))location.href=`quote.html?id=${row.dataset.id}`}))}
function plusDays(days){const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function options(rows,label,selected=''){return '<option value="">Non-defined</option>'+rows.map(row=>`<option value="${row.id}" ${row.id===selected?'selected':''}>${esc(row[label])}</option>`).join('')}
async function loadClientDependencies(){const clientId=document.getElementById('q-client').value;if(!clientId){accounts=[];contacts=[];billingEntities=[]}else{const [a,c,b]=await Promise.all([_sb.from('client_accounts').select('*').eq('client_id',clientId).eq('active',true).order('name'),_sb.from('client_contacts').select('*').eq('client_id',clientId).eq('active',true).order('full_name'),_sb.from('client_billing_entities').select('*').eq('client_id',clientId).eq('active',true).order('is_default',{ascending:false})]);accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];const client=byId(clients,clientId);document.getElementById('q-currency').value=client?.default_currency||'EUR'}document.getElementById('q-account').innerHTML=options(accounts,'name');document.getElementById('q-contact').innerHTML=options(contacts,'full_name');document.getElementById('q-billing').innerHTML=options(billingEntities,'name',billingEntities.find(e=>e.is_default)?.id||'')}
function openQuoteModal(){document.getElementById('q-client').innerHTML='<option value="">Select client…</option>'+clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');document.getElementById('q-valid').value=plusDays(30);document.getElementById('q-account').innerHTML='<option value="">Non-defined</option>';document.getElementById('q-contact').innerHTML='<option value="">Non-defined</option>';document.getElementById('q-billing').innerHTML='<option value="">Default billing entity</option>';document.getElementById('quoteModal').classList.remove('hidden')}
function closeQuoteModal(){document.getElementById('quoteModal').classList.add('hidden');document.getElementById('quoteCreateError').classList.add('hidden')}
async function createQuote(){const clientId=document.getElementById('q-client').value,errorEl=document.getElementById('quoteCreateError'),button=document.getElementById('createQuoteBtn');if(!clientId){errorEl.textContent='Client is required.';errorEl.classList.remove('hidden');return}button.disabled=true;button.textContent='Creating…';const numberResult=await _sb.rpc('next_quote_number',{p_quote_date:new Date().toISOString().slice(0,10)});if(numberResult.error){button.disabled=false;button.textContent='Create quote';errorEl.textContent=numberResult.error.message;errorEl.classList.remove('hidden');return}const {data,error}=await _sb.from('quotes').insert({quote_number:numberResult.data,client_id:clientId,account_id:document.getElementById('q-account').value||null,contact_id:document.getElementById('q-contact').value||null,billing_entity_id:document.getElementById('q-billing').value||null,title:document.getElementById('q-title').value.trim()||null,client_reference:document.getElementById('q-reference').value.trim()||null,email_reference:document.getElementById('q-email-ref').value.trim()||null,source_language:document.getElementById('q-source').value.trim()||null,currency:document.getElementById('q-currency').value,requested_deadline:document.getElementById('q-deadline').value||null,valid_until:document.getElementById('q-valid').value,created_by:(await _sb.auth.getUser()).data.user?.id||null}).select('id').single();button.disabled=false;button.textContent='Create quote';if(error){errorEl.textContent=error.message;errorEl.classList.remove('hidden');return}location.href=`quote.html?id=${data.id}`}
async function load(){const [q,c,i]=await Promise.all([_sb.from('quotes').select('*, clients(name,code), client_accounts(name)').order('created_at',{ascending:false}),_sb.from('clients').select('*').eq('restriction_status','Active').order('name'),_sb.from('quote_items').select('quote_id,target_language')]);if(q.error){document.getElementById('quotesTbody').innerHTML=`<tr class="state-row"><td colspan="9">${esc(q.error.message)}</td></tr>`;return}quotes=q.data||[];clients=c.data||[];quoteItems=i.data||[];renderQuotes()}
document.getElementById('quoteSearch').addEventListener('input',renderQuotes);document.getElementById('quoteStatus').addEventListener('change',renderQuotes);document.getElementById('q-client').addEventListener('change',loadClientDependencies);
(async()=>{const user=await requireAuth();if(user)await load()})();
