const LANGUAGE_CODES = {
    'English': 'EN', 'English (US)': 'EN-US', 'English (UK)': 'EN-GB',
    'Swedish': 'SV', 'Danish': 'DA', 'Norwegian': 'NO', 'Norwegian (Bokmål)': 'NB',
    'Finnish': 'FI', 'Icelandic': 'IS', 'Dutch': 'NL', 'Bulgarian': 'BG',
    'German': 'DE', 'French': 'FR', 'Spanish': 'ES', 'Italian': 'IT',
};
let quoteId, quote, items = [], accounts = [], contacts = [], billingEntities = [];
let specializations = [], rateCards = [], rateItems = [], projects = [];
let accountSpecializations = [];
const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const val = id => document.getElementById(id).value.trim();
const nullable = id => val(id) || null;
const money = amount => `${Number(amount || 0).toFixed(2)} ${quote?.currency || 'EUR'}`;
function toggleSub(id,item){document.getElementById(id).classList.toggle('open');item.classList.toggle('open')}
function toLocalDT(iso){if(!iso)return '';const d=new Date(iso),pad=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
const datePart=iso=>toLocalDT(iso).slice(0,10);
const timePart=iso=>toLocalDT(iso).slice(11,16);
const combineDateTime=(dateId,timeId)=>{const date=val(dateId);return date?`${date}T${val(timeId)||'17:00'}`:null};
function setStatus(message){const el=document.getElementById('saveStatus');el.textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>el.textContent='',3500)}
function error(message){const el=document.getElementById('quoteError');el.textContent=message;el.classList.remove('hidden');el.scrollIntoView({behavior:'smooth'})}
function modalError(message){const el=document.getElementById('itemError');el.textContent=message;el.classList.remove('hidden')}
function options(rows,label,selected='',empty='Non-defined'){return `<option value="">${empty}</option>`+rows.map(row=>`<option value="${row.id}" ${row.id===selected?'selected':''}>${esc(row[label])}</option>`).join('')}
function installLanguageShortcut(select){if(select.dataset.languageShortcut)return;select.dataset.languageShortcut='true';const singleKey={s:'Swedish',d:'Danish',n:'Norwegian',b:'Bulgarian',g:'German',f:'Finnish',i:'Icelandic'};let buffer='',timer;select.addEventListener('keydown',event=>{if(event.ctrlKey||event.altKey||event.metaKey||event.key.length!==1)return;const key=event.key.toLowerCase();buffer+=key;clearTimeout(timer);timer=setTimeout(()=>buffer='',800);const wanted=buffer.length===1?singleKey[key]:null;const option=[...select.options].find(item=>wanted?item.text.startsWith(wanted):item.text.toLowerCase().startsWith(buffer));if(option){event.preventDefault();select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}))}})}
function populate(){const name=`${quote.quote_number}${quote.title?' · '+quote.title:''}`;document.title=`${quote.quote_number} — RetodoOps TMS`;document.getElementById('quoteTitle').textContent=name;document.getElementById('quoteBreadcrumb').textContent=quote.quote_number;document.getElementById('quoteSubtitle').textContent=`${quote.clients?.name||''} · ${quote.status}`;const fields={'g-number':quote.quote_number,'g-client':quote.clients?.name,'g-status':quote.status,'g-title':quote.title,'g-reference':quote.client_reference,'g-email':quote.email_reference,'g-source':quote.source_language,'g-currency':quote.currency,'g-deadline-date':datePart(quote.requested_deadline),'g-deadline-time':timePart(quote.requested_deadline),'g-valid':quote.valid_until,'g-discount':quote.discount_amount,'g-notes':quote.notes};Object.entries(fields).forEach(([id,value])=>{const el=document.getElementById(id);if(id==='g-status'&&quote.status==='Accepted'&&!([...el.options].some(o=>o.value==='Accepted'))){el.add(new Option('Accepted','Accepted'))}el.value=value??''});document.getElementById('g-account').innerHTML=options(accounts,'name',quote.account_id);document.getElementById('g-contact').innerHTML=options(contacts,'full_name',quote.contact_id);document.getElementById('g-billing').innerHTML=options(billingEntities,'name',quote.billing_entity_id,'Default billing entity');document.getElementById('subtotal').textContent=money(quote.subtotal);document.getElementById('discount').textContent=money(quote.discount_amount);document.getElementById('total').textContent=money(quote.total);const locked=quote.status==='Accepted';document.getElementById('saveQuoteBtn').disabled=locked;document.getElementById('acceptQuoteBtn').disabled=locked||!items.length;document.getElementById('acceptQuoteBtn').textContent=locked?'Accepted ✓':'Accept and create projects';document.getElementById('addItemBtn').disabled=locked}
function specializationName(id){return specializations.find(s=>s.id===id)?.name||'Any'}
function renderItems(){document.getElementById('itemCount').textContent=items.length;const body=document.getElementById('itemsTbody');if(!items.length){body.innerHTML='<tr class="state-row"><td colspan="8">No quote items yet.</td></tr>';return}body.innerHTML=items.map(item=>`<tr class="clickable-row" data-id="${item.id}"><td>${esc(item.target_language)}</td><td>${esc(item.service_type)}</td><td>${esc(specializationName(item.specialization_id))}</td><td class="number-cell">${item.quantity??'—'}</td><td>${esc(item.unit||'—')}${item.cat_band?`<div class="customer-sub">${esc(item.cat_band)}</div>`:''}</td><td class="number-cell">${money(item.unit_price)}</td><td class="number-cell">${money(item.amount)}</td><td>${esc(item.rate_source||'—')}</td></tr>`).join('');if(quote.status!=='Accepted')body.querySelectorAll('tr').forEach(row=>row.addEventListener('click',()=>openItemModal(row.dataset.id)))}
function renderProjects(){document.getElementById('projectCount').textContent=projects.length;const body=document.getElementById('projectsTbody');if(!projects.length){body.innerHTML='<tr class="state-row"><td colspan="5">No Projects created yet.</td></tr>';return}body.innerHTML=projects.map(project=>`<tr><td><a class="proj-num" href="project.html?id=${project.id}">${esc(project.display_name||project.project_number)}</a></td><td>${esc(project.target_language||'—')}</td><td>${esc(project.status)}</td><td>${project.deadline?new Date(project.deadline).toLocaleString('en-GB'):'—'}</td><td class="number-cell">${Number(project.price||0).toFixed(2)} ${esc(project.currency)}</td></tr>`).join('')}
async function saveQuote(){if(quote.status==='Accepted')return;const discount=Number(val('g-discount')||0),accountId=nullable('g-account');if(accountId){const allowed=new Set(accountSpecializations.filter(link=>link.account_id===accountId).map(link=>link.specialization_id));if(!allowed.size)return error('Configure at least one specialization on the selected Account.');if(items.some(item=>!allowed.has(item.specialization_id)))return error('Existing Quote items use a specialization outside the selected Account. Edit those items before saving.')}const payload={account_id:accountId,contact_id:nullable('g-contact'),billing_entity_id:nullable('g-billing'),status:val('g-status'),title:nullable('g-title'),client_reference:nullable('g-reference'),email_reference:nullable('g-email'),source_language:nullable('g-source'),currency:val('g-currency'),requested_deadline:combineDateTime('g-deadline-date','g-deadline-time'),valid_until:val('g-valid'),discount_amount:discount,notes:nullable('g-notes')};const {error:saveError}=await _sb.from('quotes').update(payload).eq('id',quoteId);if(saveError)return error(saveError.message);await load();setStatus('Saved ✓')}
function allowedQuoteSpecializations(){const accountId=val('g-account');if(!accountId)return specializations;const ids=new Set(accountSpecializations.filter(link=>link.account_id===accountId).map(link=>link.specialization_id));return specializations.filter(spec=>ids.has(spec.id))}
function itemOptions(){const target=document.getElementById('i-target');target.innerHTML='<option value="">Select…</option>'+Object.entries(LANGUAGE_CODES).filter(([name])=>!name.startsWith('English')).map(([name,code])=>`<option value="${esc(name)}" data-code="${code}">${esc(name)}</option>`).join('');installLanguageShortcut(target);document.getElementById('i-specialization').innerHTML='<option value="">Select specialization…</option>'+allowedQuoteSpecializations().map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
function calculateAmount(){const quantity=Number(val('i-quantity')||0),unitPrice=Number(val('i-unit-price')||0);if(quantity||val('i-unit')==='Fixed fee')document.getElementById('i-amount').value=(val('i-unit')==='Fixed fee'?unitPrice:quantity*unitPrice).toFixed(2)}
function openItemModal(itemId=null){if(quote.status==='Accepted')return;const item=items.find(row=>row.id===itemId);itemOptions();document.getElementById('itemModalTitle').textContent=item?'Edit quote item':'Add quote item';const fields={'i-id':item?.id,'i-target':item?.target_language,'i-service':item?.service_type||'Translation','i-specialization':item?.specialization_id,'i-quantity':item?.quantity,'i-unit':item?.unit||'Source words','i-band':item?.cat_band,'i-unit-price':item?.unit_price,'i-amount':item?.amount,'i-rate-source':item?.rate_source||'Manual','i-override':item?.override_reason};Object.entries(fields).forEach(([id,value])=>document.getElementById(id).value=value??'');document.getElementById('itemModal').classList.remove('hidden')}
function closeItemModal(){document.getElementById('itemModal').classList.add('hidden');document.getElementById('itemError').classList.add('hidden')}
function matchRate(){const target=val('i-target'),service=val('i-service'),unit=val('i-unit'),spec=val('i-specialization'),band=val('i-band').toLowerCase(),source=quote.source_language||'';const today=new Date().toISOString().slice(0,10);const cards=rateCards.filter(card=>card.active&&(!card.valid_from||card.valid_from<=today)&&(!card.valid_to||card.valid_to>=today)&&(card.account_id===quote.account_id||!card.account_id)).sort((a,b)=>Number(b.account_id===quote.account_id)-Number(a.account_id===quote.account_id));for(const card of cards){const matches=rateItems.filter(rate=>rate.rate_card_id===card.id&&rate.service_type===service&&rate.unit===unit&&(!rate.target_language||rate.target_language===target)&&(!rate.source_language||source.includes(rate.source_language)||rate.source_language.includes(source))&&(!rate.specialization_id||rate.specialization_id===spec)&&(!rate.cat_band||rate.cat_band.toLowerCase()===band)).sort((a,b)=>Number(!!b.specialization_id)-Number(!!a.specialization_id)+Number(!!b.target_language)-Number(!!a.target_language));if(matches.length)return {rate:matches[0],source:card.account_id?'Account':'Client'}}return null}
function loadSuggestedRate(){const match=matchRate();if(!match)return modalError('No matching active Account or Client rate was found. Enter a manual/fixed price and provide a reason.');document.getElementById('i-unit-price').value=match.rate.rate;document.getElementById('i-rate-source').value=match.source;document.getElementById('i-override').value='';calculateAmount();document.getElementById('itemError').classList.add('hidden')}
async function saveItem(){const itemId=val('i-id'),targetSelect=document.getElementById('i-target'),target=targetSelect.value,unitPrice=Number(val('i-unit-price')),amount=Number(val('i-amount')),rateSource=val('i-rate-source');if(!target||!val('i-specialization')||val('i-unit-price')===''||Number.isNaN(unitPrice)||val('i-amount')===''||Number.isNaN(amount))return modalError('Target language, specialization, unit price and amount are required.');if(['Manual','Fixed'].includes(rateSource)&&!val('i-override'))return modalError('Explain why a manual or fixed price is being used.');const payload={quote_id:quoteId,target_language:target,target_language_code:targetSelect.selectedOptions[0].dataset.code,service_type:val('i-service'),specialization_id:val('i-specialization'),quantity:val('i-quantity')===''?null:Number(val('i-quantity')),unit:val('i-unit'),cat_band:nullable('i-band'),unit_price:unitPrice,amount,rate_source:rateSource,override_reason:nullable('i-override')};const {error:saveError}=itemId?await _sb.from('quote_items').update(payload).eq('id',itemId):await _sb.from('quote_items').insert(payload);if(saveError)return modalError(saveError.message);closeItemModal();await load();setStatus('Item saved ✓')}
async function acceptQuote(){if(!items.length)return error('Add at least one quote item first.');if(!confirm(`Accept ${quote.quote_number} and create one Project per target language?`))return;const button=document.getElementById('acceptQuoteBtn');button.disabled=true;button.textContent='Creating Projects…';const {data,error:acceptError}=await _sb.rpc('accept_quote',{p_quote_id:quoteId});if(acceptError){button.disabled=false;button.textContent='Accept and create projects';return error(acceptError.message)}await load();setStatus(`${data?.length||0} Project${data?.length===1?'':'s'} created ✓`)}
async function load(){const q=await _sb.from('quotes').select('*, clients(name,code)').eq('id',quoteId).single();if(q.error)return error(q.error.message);quote=q.data;const [a,c,b,s,qi,rc,ri,p,as]=await Promise.all([_sb.from('client_accounts').select('*').eq('client_id',quote.client_id).eq('active',true).order('name'),_sb.from('client_contacts').select('*').eq('client_id',quote.client_id).eq('active',true).order('full_name'),_sb.from('client_billing_entities').select('*').eq('client_id',quote.client_id).order('is_default',{ascending:false}),_sb.from('specializations').select('*').eq('active',true).order('name'),_sb.from('quote_items').select('*').eq('quote_id',quoteId).order('sort_order'),_sb.from('client_rate_cards').select('*').eq('client_id',quote.client_id).eq('active',true),_sb.from('client_rate_items').select('*'),_sb.from('projects').select('*').eq('quote_id',quoteId).order('target_language'),_sb.from('client_account_specializations').select('account_id,specialization_id')]);accounts=a.data||[];contacts=c.data||[];billingEntities=b.data||[];specializations=s.data||[];items=qi.data||[];rateCards=rc.data||[];accountSpecializations=as.data||[];const cardIds=new Set(rateCards.map(card=>card.id));rateItems=(ri.data||[]).filter(item=>cardIds.has(item.rate_card_id));projects=p.data||[];populate();renderItems();renderProjects()}
document.querySelectorAll('.record-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.record-pane').forEach(p=>p.classList.toggle('active',p.id===`pane-${tab.dataset.tab}`))}));['i-quantity','i-unit-price','i-unit'].forEach(id=>document.getElementById(id).addEventListener('input',calculateAmount));
(async()=>{const user=await requireAuth();if(!user)return;quoteId=new URLSearchParams(location.search).get('id');if(!quoteId){location.href='quotes.html';return}await load()})();
