let resourceId, resource, appRole = 'user', cvData = null;
let pairs=[], services=[], specializations=[], resourceSpecializations=[], rates=[], education=[], documents=[], history=[], availability=[], privateNotes=[];
const esc=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const el=id=>document.getElementById(id), val=id=>el(id).value.trim(), nullable=id=>val(id)||null;
function toggleSub(id,item){el(id).classList.toggle('open');item.classList.toggle('open')}
function closeModal(id){el(id).classList.add('hidden');el(id).querySelectorAll('.error-msg').forEach(x=>x.classList.add('hidden'))}
function modalError(id,message){el(id).textContent=message;el(id).classList.remove('hidden')}
function showError(message){el('resourceError').textContent=message;el('resourceError').classList.remove('hidden');el('resourceError').scrollIntoView({behavior:'smooth'})}
function setStatus(message){el('saveStatus').textContent=message;clearTimeout(setStatus.timer);setStatus.timer=setTimeout(()=>el('saveStatus').textContent='',3500)}
function fmtDate(value){return value?new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'—'}
function fmtDateTime(value){return value?new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'}
function toLocalDT(iso){if(!iso)return '';const d=new Date(iso),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`}
function money(amount,currency='EUR'){return `${Number(amount||0).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')} ${currency}`}
function specName(id){return specializations.find(row=>row.id===id)?.name||'Non-defined'}
function approvalPill(approved){return `<span class="pill ${approved?'pill-green':'pill-amber'}">${approved?'Approved':'Not approved'}</span>`}

function populateOverview(){
    const name=resource.legal_name||resource.company_name||resource.internal_number;document.title=`${name} — RetodoOps TMS`;el('resourceTitle').textContent=name;el('resourceBreadcrumb').textContent=resource.internal_number;el('resourceSubtitle').textContent=`${resource.internal_number} · ${resource.resource_type} · ${resource.classification}`;
    const fields={'r-number':resource.internal_number,'r-legacy':resource.legacy_id,'r-type':resource.resource_type,'r-name':resource.legal_name,'r-initials':resource.initials,'r-company':resource.company_name,'r-nationality':resource.nationality,'r-country':resource.country_of_residence,'r-city':resource.city,'r-native':resource.native_language,'r-timezone':resource.timezone,'r-email':resource.email,'r-phone':resource.phone,'r-website':resource.website,'r-linkedin':resource.linkedin_url,'r-linkedin-confidence':resource.linkedin_match_confidence,'r-linkedin-status':resource.linkedin_connection_status,'r-relationship':resource.relationship_status,'r-classification':resource.classification,'r-eligibility':resource.eligibility_status,'r-compliance':resource.compliance_status,'r-compliance-expiry':resource.compliance_expiry,'r-quality':resource.quality_rating,'r-restrictions':resource.operational_restrictions||resource.restriction_reason,'r-quality-evidence':resource.quality_evidence,'r-notes':resource.notes,'r-portal':resource.portal_status,'r-financial-until':resource.financial_access_until,'r-payment-days':resource.payment_terms_days,'r-invoice-cycle':resource.invoice_cycle,'r-tax':resource.tax_id,'r-cv-status':resource.blind_cv_status};Object.entries(fields).forEach(([id,value])=>el(id).value=value??'');el('r-assignment').checked=!!resource.assignment_approved;el('r-priority').checked=!!resource.priority_resource;
    const currentAvailability=availability.find(row=>new Date(row.starts_at)<=new Date()&&(!row.ends_at||new Date(row.ends_at)>=new Date()));
    el('resourceSummary').innerHTML=`<div><span>Eligibility</span><strong>${esc(resource.eligibility_status)}</strong><small>${resource.assignment_approved?'Assignment approved':'Approval required'}</small></div><div><span>Availability</span><strong>${esc(currentAvailability?.status||'Unknown')}</strong><small>${currentAvailability?.ends_at?`Until ${fmtDate(currentAvailability.ends_at)}`:'No current end date'}</small></div><div><span>Last recorded work</span><strong>${fmtDate(resource.last_recorded_job)}</strong><small>${history.length} history record${history.length===1?'':'s'}</small></div><div><span>Blind CV</span><strong>${esc(resource.blind_cv_status||'Not ready')}</strong><small>${education.length} education record${education.length===1?'':'s'}</small></div>`;
}

async function saveOverview(){const payload={resource_type:val('r-type'),legal_name:nullable('r-name'),company_name:nullable('r-company'),initials:nullable('r-initials'),nationality:nullable('r-nationality'),country_of_residence:nullable('r-country'),city:nullable('r-city'),native_language:nullable('r-native'),timezone:nullable('r-timezone'),email:nullable('r-email'),phone:nullable('r-phone'),website:nullable('r-website'),linkedin_url:nullable('r-linkedin'),linkedin_match_confidence:nullable('r-linkedin-confidence'),linkedin_connection_status:nullable('r-linkedin-status'),relationship_status:nullable('r-relationship'),classification:val('r-classification'),eligibility_status:val('r-eligibility'),compliance_status:val('r-compliance'),compliance_expiry:val('r-compliance-expiry')||null,quality_rating:val('r-quality')===''?null:Number(val('r-quality')),operational_restrictions:nullable('r-restrictions'),quality_evidence:nullable('r-quality-evidence'),notes:nullable('r-notes'),assignment_approved:el('r-assignment').checked,priority_resource:el('r-priority').checked,portal_status:val('r-portal'),financial_access_until:val('r-financial-until')||null,payment_terms_days:Number(val('r-payment-days')||60),invoice_cycle:nullable('r-invoice-cycle'),tax_id:nullable('r-tax'),blind_cv_status:val('r-cv-status')};const {error}=await _sb.from('resources').update(payload).eq('id',resourceId);if(error)return showError(error.message);await loadResource();setStatus('Saved ✓')}

function renderPairs(){el('pairsList').innerHTML=pairs.length?pairs.map(pair=>`<div class="data-card"><div><strong>${esc(pair.source_language)} → ${esc(pair.target_language)}</strong><small>${pair.native_target?'Native target · ':''}${esc(pair.notes||'')}</small></div>${approvalPill(pair.approved)}</div>`).join(''):'<div class="empty-compact">No language pairs.</div>'}
function openPairModal(){['pair-source','pair-target','pair-notes'].forEach(id=>el(id).value='');el('pair-native').checked=false;el('pair-approved').checked=false;el('pairModal').classList.remove('hidden')}
async function savePair(){if(!val('pair-source')||!val('pair-target'))return modalError('pairError','Source and target are required.');const {error}=await _sb.from('resource_language_pairs').insert({resource_id:resourceId,source_language:val('pair-source'),target_language:val('pair-target'),native_target:el('pair-native').checked,approved:el('pair-approved').checked,notes:nullable('pair-notes')});if(error)return modalError('pairError',error.message);closeModal('pairModal');await loadResource();setStatus('Language pair added ✓')}
function renderServices(){el('servicesList').innerHTML=services.length?services.map(service=>`<div class="data-card"><div><strong>${esc(service.service_type)}</strong><small>${esc(service.notes||'')}</small></div>${approvalPill(service.approved)}</div>`).join(''):'<div class="empty-compact">No services.</div>'}
function openServiceModal(){el('service-approved').checked=false;el('service-notes').value='';el('serviceModal').classList.remove('hidden')}
async function saveService(){const {error}=await _sb.from('resource_services').insert({resource_id:resourceId,service_type:val('service-name'),approved:el('service-approved').checked,notes:nullable('service-notes')});if(error)return modalError('serviceError',error.message);closeModal('serviceModal');await loadResource();setStatus('Service added ✓')}

function renderSpecializations(){const body=el('specializationsTbody');body.innerHTML=resourceSpecializations.length?resourceSpecializations.map(row=>`<tr><td>${esc(specName(row.specialization_id))}</td><td>${row.experience_years??'—'}${row.experience_years!=null?' years':''}</td><td>${approvalPill(row.approved)}</td><td>${esc(row.evidence||'—')}</td></tr>`).join(''):'<tr class="state-row"><td colspan="4">No specializations.</td></tr>'}
function specOptions(selected=''){return '<option value="">Non-defined</option>'+specializations.map(spec=>`<option value="${spec.id}" ${spec.id===selected?'selected':''}>${esc(spec.name)}</option>`).join('')}
function openSpecializationModal(){el('spec-id').innerHTML=specOptions();el('spec-years').value='';el('spec-evidence').value='';el('spec-approved').checked=false;el('specializationModal').classList.remove('hidden')}
async function saveSpecialization(){if(!val('spec-id'))return modalError('specError','Select a specialization.');const {error}=await _sb.from('resource_specializations').insert({resource_id:resourceId,specialization_id:val('spec-id'),experience_years:val('spec-years')===''?null:Number(val('spec-years')),approved:el('spec-approved').checked,evidence:nullable('spec-evidence')});if(error)return modalError('specError',error.message);closeModal('specializationModal');await loadResource();setStatus('Specialization added ✓')}

function renderRates(){el('ratesTbody').innerHTML=rates.length?rates.map(rate=>`<tr><td>${esc(rate.source_language||'Any')} → ${esc(rate.target_language||'Any')}</td><td>${esc(rate.service_type)}</td><td>${esc(specName(rate.specialization_id))}</td><td>${esc(rate.unit)}${rate.cat_band?`<div class="customer-sub">${esc(rate.cat_band)}</div>`:''}</td><td>${money(rate.rate,rate.currency)}</td><td>${rate.minimum_fee==null?'—':Number(rate.minimum_fee).toFixed(2)+' '+rate.currency}</td><td>${fmtDate(rate.valid_from)} – ${fmtDate(rate.valid_to)}</td><td><span class="pill ${rate.status==='Approved'?'pill-green':rate.status==='Rejected'?'pill-red':'pill-amber'}">${esc(rate.status)}</span></td></tr>`).join(''):'<tr class="state-row"><td colspan="8">No rates.</td></tr>'}
function openRateModal(){['rate-source','rate-target','rate-band','rate-value','rate-minimum','rate-from','rate-to'].forEach(id=>el(id).value='');el('rate-spec').innerHTML=specOptions();el('rate-status').value='Pending';el('rateModal').classList.remove('hidden')}
async function saveRate(){if(val('rate-value')==='')return modalError('rateError','Enter a rate.');const payload={resource_id:resourceId,source_language:nullable('rate-source'),target_language:nullable('rate-target'),service_type:val('rate-service'),specialization_id:nullable('rate-spec'),unit:val('rate-unit'),cat_band:nullable('rate-band'),rate:Number(val('rate-value')),currency:val('rate-currency'),minimum_fee:val('rate-minimum')===''?null:Number(val('rate-minimum')),valid_from:val('rate-from')||null,valid_to:val('rate-to')||null,status:val('rate-status')};const {error}=await _sb.from('resource_rates').insert(payload);if(error)return modalError('rateError',error.message);closeModal('rateModal');await loadResource();setStatus('Rate added ✓')}

function renderEducation(){el('educationList').innerHTML=education.length?education.map(row=>`<div class="data-card"><div><strong>${esc(row.degree||'Degree not specified')}${row.field_of_study?` · ${esc(row.field_of_study)}`:''}</strong><small>${esc(row.institution||'Institution not specified')} · ${row.start_year||'—'}–${row.end_year||'—'}</small></div>${approvalPill(row.verified)}</div>`).join(''):'<div class="empty-compact">No education records.</div>';el('documentsList').innerHTML=documents.length?documents.map(row=>`<div class="data-card"><div><strong>${esc(row.document_type)}</strong><small>${esc(row.status)}${row.expires_on?` · expires ${fmtDate(row.expires_on)}`:''}</small></div></div>`).join(''):'<div class="empty-compact">No document metadata.</div>'}
function openEducationModal(){['edu-institution','edu-degree','edu-field','edu-start','edu-end'].forEach(id=>el(id).value='');el('edu-verified').checked=false;el('educationModal').classList.remove('hidden')}
async function saveEducation(){const {error}=await _sb.from('resource_education').insert({resource_id:resourceId,institution:nullable('edu-institution'),degree:nullable('edu-degree'),field_of_study:nullable('edu-field'),start_year:val('edu-start')===''?null:Number(val('edu-start')),end_year:val('edu-end')===''?null:Number(val('edu-end')),verified:el('edu-verified').checked,sort_order:education.length});if(error)return modalError('educationError',error.message);closeModal('educationModal');await loadResource();setStatus('Education added ✓')}

function renderHistory(){el('historyTbody').innerHTML=history.length?history.map(row=>`<tr><td>${row.period_start?fmtDate(row.period_start):row.project_year||'—'}${row.period_end?` – ${fmtDate(row.period_end)}`:''}</td><td>${esc(row.account_display_label||'Confidential account')}</td><td>${esc(row.source_language||'—')} → ${esc(row.target_language||'—')}</td><td>${esc(row.service_type||'—')}</td><td>${esc(specName(row.specialization_id))}</td><td>${esc(row.project_summary||'—')}</td><td><input type="checkbox" ${row.include_in_blind_cv?'checked':''} onchange="toggleHistoryCv('${row.id}',this.checked)"></td></tr>`).join(''):'<tr class="state-row"><td colspan="7">No approved Job history.</td></tr>'}
async function toggleHistoryCv(id,checked){const {error}=await _sb.from('resource_project_history').update({include_in_blind_cv:checked}).eq('id',id);if(error)return showError(error.message);setStatus('CV inclusion updated ✓')}
function renderAvailability(){el('availabilityTbody').innerHTML=availability.length?availability.map(row=>`<tr><td><span class="pill ${row.status==='Available'?'pill-green':row.status==='Limited'?'pill-amber':'pill-red'}">${esc(row.status)}</span></td><td>${fmtDateTime(row.starts_at)}</td><td>${fmtDateTime(row.ends_at)}</td><td>${esc(row.notes||'—')}</td></tr>`).join(''):'<tr class="state-row"><td colspan="4">No availability records.</td></tr>'}
function openAvailabilityModal(){el('av-status').value='Available';el('av-start').value=toLocalDT(new Date().toISOString());el('av-end').value='';el('av-notes').value='';el('availabilityModal').classList.remove('hidden')}
async function saveAvailability(){if(!val('av-start'))return modalError('availabilityError','A start date is required.');const user=(await _sb.auth.getUser()).data.user;const {error}=await _sb.from('resource_availability').insert({resource_id:resourceId,status:val('av-status'),starts_at:val('av-start'),ends_at:val('av-end')||null,notes:nullable('av-notes'),created_by:user?.id||null});if(error)return modalError('availabilityError',error.message);closeModal('availabilityModal');await loadResource();setStatus('Availability added ✓')}

function renderPrivateNotes(){if(appRole!=='admin')return;el('privateArchiveCard').classList.remove('hidden');el('privateNotesList').innerHTML=privateNotes.length?privateNotes.map(row=>`<div class="private-note"><strong>${esc(row.note_type)}</strong><span>${fmtDateTime(row.created_at)}</span><p>${esc(row.content)}</p>${row.source_record?`<small>${esc(row.source_record)}</small>`:''}</div>`).join(''):'<div class="empty-compact">No private archived notes.</div>'}
async function addPrivateNote(){if(!val('new-private-note'))return;const user=(await _sb.auth.getUser()).data.user;const {error}=await _sb.from('resource_private_notes').insert({resource_id:resourceId,note_type:'Private management note',content:val('new-private-note'),created_by:user?.id||null});if(error)return showError(error.message);el('new-private-note').value='';await loadResource();setStatus('Private note added ✓')}

function cvText(value,fallback='Not recorded'){return value&&String(value).trim()?String(value):fallback}
function renderBlindCvPreview(){const r=cvData.resource,lp=cvData.language_pairs||[],hist=cvData.project_history||[];el('blindCvPreview').innerHTML=`<div class="cv-brand"><strong>Retodo Ops</strong><span>Blind Linguist Profile</span></div><h2>${esc(r.internal_number)} · ${esc(cvText(r.initials))}</h2><div class="cv-meta"><span><b>Nationality:</b> ${esc(cvText(r.nationality))}</span><span><b>Residence:</b> ${esc(cvText(r.country_of_residence))}</span><span><b>Native language:</b> ${esc(cvText(r.native_language))}</span></div><h3>Language coverage</h3><p>${lp.length?lp.map(x=>`${esc(x.source)} → ${esc(x.target)}${x.native_target?' (native target)':''}`).join('; '):'Not recorded'}</p><h3>Services and specializations</h3><p><b>Services:</b> ${esc((cvData.services||[]).join(', ')||'Not recorded')}</p><ul>${(cvData.specializations||[]).map(x=>`<li>${esc(x.name)}${x.experience_years?` — ${x.experience_years} years`:''}</li>`).join('')||'<li>Not recorded</li>'}</ul><h3>Education</h3><ul>${(cvData.education||[]).map(x=>`<li>${esc([x.degree,x.field_of_study,x.institution].filter(Boolean).join(', '))}${x.end_year?` (${x.start_year||'—'}–${x.end_year})`:''}</li>`).join('')||'<li>Not recorded</li>'}</ul><h3>Selected project experience</h3><ul>${hist.map(x=>`<li>${esc(String(x.year||''))} · ${esc(cvText(x.account,'Confidential account'))} · ${esc(cvText(x.source_language,'—'))} → ${esc(cvText(x.target_language,'—'))} · ${esc([x.service,x.specialization].filter(Boolean).join(', '))}</li>`).join('')||'<li>No approved project history selected.</li>'}</ul><div class="cv-footer">Prepared by Retodo Ops · Personal identity and direct contact details withheld</div>`}
async function openBlindCv(){el('blindCvModal').classList.remove('hidden');el('blindCvPreview').textContent='Preparing anonymized profile…';const {data,error}=await _sb.rpc('get_blind_cv_data',{p_resource_id:resourceId});if(error){modalError('blindCvError',error.message);return}cvData=data;renderBlindCvPreview()}
function saveBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function cvLines(){const r=cvData.resource;return [{heading:'Linguist profile',lines:[`${r.internal_number} · ${cvText(r.initials)}`,`Nationality: ${cvText(r.nationality)}`,`Country of residence: ${cvText(r.country_of_residence)}`,`Native language: ${cvText(r.native_language)}`]},{heading:'Language coverage',lines:(cvData.language_pairs||[]).map(x=>`${x.source} → ${x.target}${x.native_target?' (native target)':''}`)},{heading:'Services',lines:cvData.services||[]},{heading:'Specializations',lines:(cvData.specializations||[]).map(x=>`${x.name}${x.experience_years?` — ${x.experience_years} years`:''}`)},{heading:'Education',lines:(cvData.education||[]).map(x=>[x.degree,x.field_of_study,x.institution,x.start_year||x.end_year?`${x.start_year||'—'}–${x.end_year||'—'}`:''].filter(Boolean).join(', '))},{heading:'Selected project experience',lines:(cvData.project_history||[]).map(x=>`${x.year||''} · ${cvText(x.account,'Confidential account')} · ${cvText(x.source_language,'—')} → ${cvText(x.target_language,'—')} · ${[x.service,x.specialization].filter(Boolean).join(', ')}`)}]}
async function downloadBlindCvDocx(){if(!cvData)return;try{const {Document,Packer,Paragraph,TextRun,HeadingLevel,AlignmentType}=window.docx;const children=[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'Retodo Ops',bold:true,size:32,color:'1E1248'})]}),new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({text:'BLIND LINGUIST PROFILE',bold:true,size:22,color:'7C3AED'})]})];cvLines().forEach(section=>{children.push(new Paragraph({text:section.heading,heading:HeadingLevel.HEADING_2,spacing:{before:240,after:80}}));(section.lines.length?section.lines:['Not recorded']).forEach(line=>children.push(new Paragraph({text:line,bullet:section.heading==='Linguist profile'?undefined:{level:0}}))) });children.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:320},children:[new TextRun({text:'Personal identity and direct contact details withheld',italics:true,color:'6B7280',size:18})]}));const doc=new Document({sections:[{properties:{},children}]});saveBlob(await Packer.toBlob(doc),`Blind_CV_${cvData.resource.internal_number}.docx`)}catch(error){modalError('blindCvError',`DOCX generation failed: ${error.message}`)}}
async function downloadBlindCvPdf(){if(!cvData)return;try{await window.html2pdf().set({margin:[10,10,10,10],filename:`Blind_CV_${cvData.resource.internal_number}.pdf`,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'},pagebreak:{mode:['css','legacy']}}).from(el('blindCvPreview')).save()}catch(error){modalError('blindCvError',`PDF generation failed: ${error.message}`)}}

async function loadResource(){const base=await _sb.from('resources').select('*').eq('id',resourceId).single();if(base.error)return showError(base.error.message);resource=base.data;const requests=[_sb.from('resource_language_pairs').select('*').eq('resource_id',resourceId).order('target_language'),_sb.from('resource_services').select('*').eq('resource_id',resourceId).order('service_type'),_sb.from('specializations').select('*').eq('active',true).order('name'),_sb.from('resource_specializations').select('*').eq('resource_id',resourceId),_sb.from('resource_rates').select('*').eq('resource_id',resourceId).order('created_at',{ascending:false}),_sb.from('resource_education').select('*').eq('resource_id',resourceId).order('sort_order'),_sb.from('resource_documents').select('*').eq('resource_id',resourceId).order('created_at',{ascending:false}),_sb.from('resource_project_history').select('*').eq('resource_id',resourceId).order('project_year',{ascending:false}),_sb.from('resource_availability').select('*').eq('resource_id',resourceId).order('starts_at',{ascending:false})];if(appRole==='admin')requests.push(_sb.from('resource_private_notes').select('*').eq('resource_id',resourceId).order('created_at',{ascending:false}));const result=await Promise.all(requests);[pairs,services,specializations,resourceSpecializations,rates,education,documents,history,availability]=result.slice(0,9).map(x=>x.data||[]);privateNotes=appRole==='admin'?(result[9]?.data||[]):[];populateOverview();renderPairs();renderServices();renderSpecializations();renderRates();renderEducation();renderHistory();renderAvailability();renderPrivateNotes()}

document.querySelectorAll('.record-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.record-tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.record-pane').forEach(pane=>pane.classList.toggle('active',pane.id===`pane-${tab.dataset.tab}`))}));
(async()=>{const user=await requireAuth();if(!user)return;resourceId=new URLSearchParams(location.search).get('id');if(!resourceId){location.href='resources.html?type=external';return}const role=await _sb.rpc('current_app_role');appRole=role.data||'user';await loadResource()})();
