'use strict';
/* Update 063: admin Sales workspace. Database RPCs enforce every write rule. */
const SALES={data:null,tab:new URLSearchParams(location.search).get('tab')||'today',query:'',offset:0,selected:new Map(),detail:null,service:null,loading:0,dialogSubmit:null,dirty:false,settingsDirty:false,aiIds:new Map()};
const salesEl=id=>document.getElementById(id);
const salesEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const salesDate=v=>v?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'Not yet';
const salesMoney=v=>new Intl.NumberFormat(undefined,{style:'currency',currency:'EUR',maximumFractionDigits:2}).format(Number(v)||0);
const salesLocal=v=>{const d=new Date(v||Date.now());return new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const salesPill=(text,tone='')=>`<span class="sales-pill ${salesEsc(tone)}">${salesEsc(text)}</span>`;
const salesBtn=(label,action,id='',primary=false)=>`<button type="button" class="${primary?'btn-primary':'btn-secondary'}" data-action="${action}" data-id="${salesEsc(id)}">${salesEsc(label)}</button>`;
function salesLink(url,label){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return '';return `<a href="${salesEsc(u.href)}" target="_blank" rel="noopener noreferrer">${salesEsc(label||u.hostname)}</a>`;}catch{return '';}}
function toggleSub(id,item){salesEl(id)?.classList.toggle('open');item?.classList.toggle('open');}
function salesNotice(message,error=false){const e=salesEl('salesNotice');e.textContent=message;e.className='sales-notice'+(error?' error':'');}
async function salesRpc(name,args={}){const {data,error}=await _sb.rpc(name,args);if(error)throw error;return data;}
const salesCommand=(action,data={})=>salesRpc('sales_command_063',{p_action:action,p_data:data});
async function salesApi(action,data={}){
 const {data:{session}}=await _sb.auth.getSession();if(!session?.access_token)throw new Error('Sign in again to continue');
 const res=await fetch('/.netlify/functions/sales',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...data}),signal:AbortSignal.timeout(30000)});
 let result;try{result=await res.json();}catch{throw new Error('Sales services are unavailable. Check the Update 063 function installation');}
 if(!res.ok)throw new Error(result.error||'Sales request failed');return result;
}
function salesField(label,name,value='',type='text',full=false,extra=''){
 return `<label class="sales-field${full?' full':''}"><span>${salesEsc(label)}</span>${type==='textarea'?`<textarea name="${name}" ${/rows=/.test(extra)?'':'rows="5"'} ${extra}>${salesEsc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${salesEsc(value)}" ${extra}>`}</label>`;
}
function salesForm(){return Object.fromEntries(new FormData(salesEl('salesDialogForm')));}
function salesDialog(title,body,footer,submit){
 const dialog=salesEl('salesDialog');salesEl('salesDialogTitle').textContent=title;salesEl('salesDialogBody').innerHTML=body;salesEl('salesDialogFooter').innerHTML=footer;salesEl('salesDialogError').textContent='';SALES.dialogSubmit=submit;SALES.dirty=false;
 if(!dialog.open)dialog.showModal();salesEl('salesDialogBody').scrollTop=0;
}
function salesClose(force=false){if(!force&&SALES.dirty&&!confirm('Discard your unsaved changes?'))return;salesEl('salesDialog').close();SALES.dirty=false;SALES.dialogSubmit=null;}
const salesSubmit=label=>`<button class="btn-primary" type="submit">${salesEsc(label)}</button>`;

async function salesLoad({clearSelection=false,quiet=false}={}){
 const request=++SALES.loading;
 try{
  const data=await salesRpc('sales_workspace_063',{p_query:SALES.query,p_offset:SALES.offset,p_limit:50});
  if(request!==SALES.loading)return;
  SALES.data=data;if(clearSelection)SALES.selected.clear();salesRender();
 }catch(e){if(!quiet){salesNotice(e.code==='PGRST202'?'Sales needs migration 057. Install the database update first.':e.message,true);if(!SALES.data)salesEl('salesView').innerHTML='<div class="sales-empty">Sales could not load. Your existing TMS modules remain available.</div>';}}
}
function salesSetTab(tab){
 if(SALES.tab==='settings'&&SALES.settingsDirty&&!confirm('Discard your unsaved settings?'))return;
 SALES.dirty=false;SALES.settingsDirty=false;SALES.tab=['today','prospects','review','conversations','materials','settings'].includes(tab)?tab:'today';
 history.replaceState(null,'',`sales.html?tab=${SALES.tab}`);salesRender();
}
function salesRender(){
 const d=SALES.data;if(!d)return;if(SALES.tab==='settings'&&SALES.settingsDirty)return;
 salesEl('salesMode').textContent=d.settings.sending_enabled?'Approved sending enabled':'Sending paused';
 salesEl('reviewCount').textContent=d.counts.review?`(${d.counts.review})`:'';
 document.querySelectorAll('[data-tab]').forEach(b=>{if(b.dataset.tab===SALES.tab)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 const render={today:salesToday,prospects:salesProspects,review:salesReview,conversations:salesConversations,materials:salesMaterials,settings:salesSettings}[SALES.tab]||salesToday;
 salesEl('salesView').innerHTML=render(d);
}
function salesBudget(d){
 const used=Number(d.budget.charged)+Number(d.budget.reserved)+Number(d.settings.recurring_eur),free=Math.max(0,Number(d.settings.monthly_cap)-Number(d.settings.reserve_eur)-used);
 return `<div class="sales-card"><h2>This month’s budget</h2><div class="sales-card-head"><strong>${salesMoney(free)} available for new work</strong><span class="sales-small">${salesMoney(d.settings.monthly_cap)} ceiling</span></div><div class="sales-budget-track"><span style="width:${Math.min(100,used/Number(d.settings.monthly_cap)*100)}%"></span></div><dl class="sales-meta"><dt>Usage estimate</dt><dd>${salesMoney(d.budget.charged)}</dd><dt>Reserved jobs</dt><dd>${salesMoney(d.budget.reserved)}</dd><dt>Other costs</dt><dd>${salesMoney(d.settings.recurring_eur)}</dd><dt>Safety reserve</dt><dd>${salesMoney(d.settings.reserve_eur)}</dd></dl><p class="sales-small">Usage uses provider tokens and a conservative currency/tax allowance. Unknown requests keep their reservation.</p></div>`;
}
function salesToday(d){
 const stats=[['prospects','Prospects'],['review','To review'],['queued','Approved queue'],['sent','Emails sent'],['replies','Replies'],['attention','Need attention']];
 const jobs=d.jobs.map(j=>`<div class="sales-row"><div class="sales-card-head"><strong>${salesEsc(j.kind==='research'?'Prospect research':j.kind==='draft'?'Outreach draft':'Sales material')}</strong>${salesPill(j.state,j.state==='completed'?'good':j.state==='uncertain'?'warn':'')}</div><p class="sales-small">${salesDate(j.created_at)} · ${j.cost_eur===null?'Reserved':'Accounted'} ${salesMoney(j.cost_eur??j.reserved_eur)}</p>${j.error?`<p>${salesEsc(j.error)}</p>`:''}${j.result?`<p>${j.kind==='research'?`${Number(j.result.imported)||0} new prospects added. Existing companies were skipped.`:j.kind==='materials'?'Saved in Materials. Review before sharing.':'Ready to review and turn into a sequence.'}</p>${salesBtn('View result','job',j.id)}`:''}</div>`).join('');
 return `<div class="sales-stats">${stats.map(([key,label])=>`<div class="sales-stat"><strong>${d.counts[key]}</strong><span>${label}</span></div>`).join('')}</div><div class="sales-grid"><div>
 <section class="sales-card"><div class="sales-card-head"><h2>Next actions</h2>${salesBtn('+ Add task','task')}</div>${d.tasks.length?d.tasks.map(t=>`<div class="sales-row"><strong>${salesEsc(t.title)}</strong><p class="sales-small">${salesEsc(t.company||'Sales')} · ${salesDate(t.due_at)}</p><p>${salesEsc(t.notes)}</p>${salesBtn('Mark done','task-done',t.id)} ${t.prospect_id?salesBtn('Open prospect','prospect',t.prospect_id):''}</div>`).join(''):'<p class="sales-muted">Your LinkedIn, vendor registration and meeting tasks will appear here.</p>'}</section>
 ${d.attention.length?`<section class="sales-card"><h2>Needs your attention</h2>${d.attention.map(m=>`<div class="sales-row"><strong>${salesEsc(m.company)} ${salesPill(m.state,'warn')}</strong><p>${salesEsc(m.last_error)}</p>${salesBtn('Open conversation','conversation',m.conversation_id)}</div>`).join('')}</section>`:''}
 <section class="sales-card"><div class="sales-card-head"><h2>Research & writing</h2>${salesBtn('Refresh','refresh')}</div>${jobs||'<p class="sales-muted">Start with Find prospects, or add a company you already know.</p>'}</section></div><div>${salesBudget(d)}
 <section class="sales-card"><h2>Automation</h2><dl class="sales-meta"><dt>Sending</dt><dd>${d.settings.sending_enabled?'Enabled for approved messages':'Paused'}</dd><dt>Daily limit</dt><dd>${d.settings.daily_limit} messages</dd><dt>Research</dt><dd>${d.settings.research_enabled?`Every ${d.settings.research_interval_days} days`:'On demand'}</dd><dt>Mailbox check</dt><dd>${salesDate(d.runtime.mailbox_checked_at)}</dd><dt>Worker</dt><dd>${salesDate(d.runtime.worker_at)}</dd></dl>${d.runtime.mailbox_error?`<p class="sales-small">${salesEsc(d.runtime.mailbox_error)}</p>`:''}${d.runtime.worker_error?`<p class="sales-small">${salesEsc(d.runtime.worker_error)}</p>`:''}<div class="sales-actions">${salesBtn('Check now','run')}${salesBtn('Settings','settings')}</div></section>
 <section class="sales-card"><h2>Recent activity</h2>${d.events.slice(0,8).map(e=>`<div class="sales-row"><strong>${salesEsc(e.event.replaceAll('_',' '))}</strong><span class="sales-small">${salesDate(e.created_at)}</span></div>`).join('')||'<p class="sales-muted">Approvals, messages and replies will be recorded here.</p>'}</section></div></div>`;
}
function salesSearchToolbar(extra=''){return `<div class="sales-toolbar"><input type="search" id="salesSearch" value="${salesEsc(SALES.query)}" placeholder="Search company or domain" aria-label="Search Sales"><button type="button" class="btn-secondary" data-action="search">Search</button>${extra}</div>`;}
function salesProspects(d){return salesSearchToolbar(salesBtn('Clear','clear-search'))+`<div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Company</th><th>Fit / sector</th><th>Stage</th><th>Evidence</th><th></th></tr></thead><tbody>${d.prospects.map(p=>`<tr><td><strong>${salesEsc(p.name)}</strong>${salesLink('https://'+p.domain,p.domain)}<div class="sales-small">${salesEsc(p.country)}</div></td><td>${salesEsc(p.sector)}<p class="sales-small">${salesEsc(p.fit_note.slice(0,160))}</p></td><td>${salesPill(p.stage,p.stage==='won'?'good':'')}${p.client_id?`<div class="sales-small"><a href="client.html?id=${encodeURIComponent(p.client_id)}">Linked Client</a></div>`:''}</td><td>${salesLink(p.source_url,'View source')}<div class="sales-small">${p.researched_at?salesDate(p.researched_at):'Manual record'}</div></td><td>${salesBtn('Open','prospect',p.id)}</td></tr>`).join('')||'<tr><td colspan="5"><div class="sales-empty"><strong>Your prospect pipeline starts here</strong>Add a company or run research with your target brief.</div></td></tr>'}</tbody></table></div><div class="sales-pagination"><span>${d.prospect_count?SALES.offset+1:0}–${Math.min(SALES.offset+50,d.prospect_count)} of ${d.prospect_count}</span><div>${salesBtn('Previous','previous')}${salesBtn('Next','next')}</div></div>`;}
function salesTiming(m){return m.kind==='followup'?`${m.delay_days} business days after the initial email sends`:salesDate(m.due_at);}
function salesMessageMeta(m){return `<dl class="sales-meta"><dt>From</dt><dd>Eli Stoyanova &lt;${salesEsc(m.sender||'eli.s@retodo-ops.com')}&gt;</dd><dt>Reply-To</dt><dd>${salesEsc(m.reply_to||'eli.s@retodo-ops.com')}</dd><dt>To</dt><dd>${salesEsc(m.recipient)}</dd><dt>Timing</dt><dd>${salesEsc(salesTiming(m))}</dd></dl>`;}
function salesFiles(m){return (m.attachments||[]).length?`<div class="sales-file-list">${m.attachments.map((a,i)=>salesBtn(`Attachment: ${a.name}`,'attachment',`${m.id}:${i}`)).join('')}</div>`:'';}
function salesReview(d){return salesSearchToolbar()+`<div class="sales-toolbar"><label class="sales-check"><input type="checkbox" id="salesSelectAll" ${d.review.length&&d.review.every(m=>SALES.selected.has(m.id))?'checked':''}>Select visible drafts (maximum 50)</label><span id="salesSelectionCount">${SALES.selected.size} selected</span>${salesBtn('Review selected batch','review-batch','',true)}</div><p class="sales-small">Initial messages and each follow-up need approval. Editing an approved message returns it to review. Reply and opt-out checks run again before sending. Showing up to 100 drafts; use search to narrow the list.</p>${d.review.map(m=>`<article class="sales-review-card ${SALES.selected.has(m.id)?'selected':''}"><div class="sales-card-head"><label class="sales-check"><input type="checkbox" data-select="${m.id}" ${SALES.selected.has(m.id)?'checked':''}><strong>${salesEsc(m.company)} · ${salesEsc(m.kind)}</strong></label>${salesBtn('Edit draft','edit-message',m.id)}</div>${salesMessageMeta(m)}<h3>${salesEsc(m.subject)}</h3><details><summary>Read complete message</summary>${salesMessageContent(m)}</details>${salesFiles(m)}<p class="sales-small">Contact ${m.verified_at?`verified ${salesDate(m.verified_at)}`:'needs verification'} · ${salesEsc(m.outreach_basis||'Outreach basis not recorded')}</p></article>`).join('')||'<div class="sales-empty"><strong>No drafts waiting for review</strong>Open a prospect to prepare a sequence.</div>'}`;}
function salesConversations(d){return salesSearchToolbar(salesBtn('Check replies','run'))+`<p class="sales-small">Most recent 100 matching conversations. Replies in Gmail also pause the sequence.</p><div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Company / contact</th><th>Status</th><th>Last checked</th><th></th></tr></thead><tbody>${d.conversations.map(c=>`<tr><td><strong>${salesEsc(c.company)}</strong>${salesEsc(c.contact_name)}<div class="sales-small">${salesEsc(c.recipient)}</div></td><td>${salesPill(c.state,c.state==='replied'?'good':c.state==='suppressed'?'bad':'')}<div class="sales-small">${salesEsc(c.pause_reason)}</div></td><td>${salesDate(c.synced_at)}${c.last_sync_error?`<p class="sales-small">${salesEsc(c.last_sync_error)}</p>`:''}</td><td>${salesBtn('Open','conversation',c.id)}</td></tr>`).join('')||'<tr><td colspan="4"><div class="sales-empty">Conversations appear when you create an outreach sequence.</div></td></tr>'}</tbody></table></div>`;}
function salesMaterials(d){return `<div class="sales-toolbar">${salesBtn('+ Write material','new-material','',true)}${salesBtn('Generate with AI','generate-material')}</div><p class="sales-small">Keep pitches and capability decks here. Edit the wording, preview the slides, then download PowerPoint, text or print to PDF. Review generated claims before sharing.</p>${d.materials.map(m=>`<section class="sales-card"><div class="sales-card-head"><div><h2>${salesEsc(m.title)}</h2><span class="sales-small">Version ${m.version} · ${salesDate(m.updated_at)}</span></div><div class="sales-actions">${salesBtn('Edit & preview','material',m.id)}${salesBtn('PowerPoint','pptx',m.id)}${salesBtn('Text','material-text',m.id)}${salesBtn('Print / PDF','material-print',m.id)}</div></div><p class="sales-small">${salesEsc(m.content.slice(0,200))}</p></section>`).join('')||'<div class="sales-empty"><strong>Your Sales material library</strong>Save approved company facts in Settings, then generate a first pitch or write your own.</div>'}`;}
function salesSettings(d){const s=d.settings;return `<form id="salesSettingsForm"><div class="sales-grid"><div><section class="sales-card"><h2>Outreach</h2><div class="sales-fields">
 <label class="sales-check sales-field full"><span><input type="checkbox" name="sending_enabled" ${s.sending_enabled?'checked':''}> Allow approved messages to send</span></label>
 ${salesField('Daily sending limit','daily_limit',s.daily_limit,'number',false,'min="1" max="30" required')}
 <div class="sales-field"><span>Sales identity</span><strong>Eli Stoyanova</strong><span class="sales-small">From and Reply-To: eli.s@retodo-ops.com</span></div></div><p class="sales-small">Turning sending on releases approved, due messages. General TMS email retains its existing sender. The pilot is administrator-only.</p>${salesBtn('Check mailbox connection','check-mailbox')}</section>
 ${salesSignatureSettings(s)}
 <section class="sales-card"><h2>Target clients</h2>${salesField('Research brief','target_brief',s.target_brief,'textarea',true,'maxlength="4000" placeholder="Company type, markets, services, evidence of demand and people to look for"')}<div class="sales-fields" style="margin-top:16px"><label class="sales-check"><input type="checkbox" name="research_enabled" ${s.research_enabled?'checked':''}>Research automatically within the budget</label>${salesField('Repeat every (days)','research_interval_days',s.research_interval_days,'number',false,'min="1" max="30" required')}</div></section>
 <section class="sales-card"><h2>Approved company facts</h2>${salesField('Facts the writing assistant may use','approved_facts',s.approved_facts,'textarea',true,'rows="9" maxlength="12000" placeholder="Verified services, language pairs, specializations, process, positioning and contact details. Include only claims you can stand behind."')}<p class="sales-small">These facts guide pitches and presentations. Leave unconfirmed certifications, capacity, rates and references out.</p></section></div><div>
 <section class="sales-card"><h2>Monthly budget</h2><div class="sales-fields">${salesField('Ceiling (EUR)','monthly_cap',s.monthly_cap,'number',false,'min="1" max="30" step="0.01" required')}${salesField('Safety reserve (EUR)','reserve_eur',s.reserve_eur,'number',false,'min="0" max="30" step="0.01" required')}${salesField('Other Sales costs (EUR/month)','recurring_eur',s.recurring_eur,'number',true,'min="0" max="30" step="0.01" required')}</div><p class="sales-small">Include incremental hosting, mail or other paid Sales services in Other Sales costs. Research reserves its upper estimate before starting. No paid task starts above the available allowance.</p></section>
 <section class="sales-card"><h2>Connections</h2>${s.budget_hold?'<p class="sales-error">AI spending is on hold because recorded usage exceeded its reservation. Review provider pricing before resetting the hold.</p>':''}<p class="sales-small">${salesEsc(SALES.service?.ai_ready?'AI is configured.':SALES.service?.ai_hold||'Checking AI availability…')}</p><p class="sales-small">${SALES.service?.worker_ready?'Background worker configured.':'Background worker setup required for research and email automation.'}</p><p class="sales-small">${d.runtime.mailbox_ok?'Mailbox check passed.':'Mailbox connection needs a successful check.'}</p>${salesBtn('Refresh connection status','status')}</section>
 <section class="sales-card"><h2>Do not contact</h2><p class="sales-small">Block an email address or a whole company domain. This also stops its pending outreach.</p>${salesBtn('Add suppression','suppress')}</section></div></div><button class="btn-primary" type="submit">Save Sales settings</button></form>`;}

async function salesOpenProspect(id){
 const detail=await salesRpc('sales_detail_063',{p_id:id});SALES.detail=detail;const p=detail.prospect;
 const stages=['research','qualified','contacted','replied','opportunity','won','lost','suppressed'];
 const contacts=detail.contacts.map(k=>`<div class="sales-row"><div class="sales-card-head"><div><strong>${salesEsc(k.name||'Contact to identify')}</strong><span class="sales-small">${salesEsc(k.role_title)} · ${salesEsc(k.email||'Email unknown')}</span></div>${salesPill(k.verified_at?'Verified':'Needs verification',k.verified_at?'good':'warn')}</div><div class="sales-actions">${salesLink(k.linkedin_url,'LinkedIn profile')} ${salesLink(k.source_url,'Evidence source')}${salesBtn('Edit contact','contact',k.id)}${salesBtn('Prepare outreach','sequence',k.id)}${salesBtn('AI draft','draft',k.id)}${salesBtn('LinkedIn task','linkedin-task',k.id)}</div></div>`).join('');
 salesDialog(p.name,`<div class="sales-fields">${salesField('Company','name',p.name,'text',false,'required maxlength="200"')}${salesField('Domain','domain',p.domain,'text',false,'required maxlength="253"')}${salesField('Country','country',p.country)}${salesField('Sector','sector',p.sector)}${salesField('Why this company fits','fit_note',p.fit_note,'textarea',true,'maxlength="4000"')}${salesField('Evidence URL','source_url',p.source_url,'url',true,'maxlength="2000"')}<label class="sales-field"><span>Stage</span><select name="stage">${stages.map(s=>`<option ${s===p.stage?'selected':''}>${s}</option>`).join('')}</select></label>${salesField('Notes','notes',p.notes,'textarea',true,'maxlength="6000"')}</div>
 <div class="sales-card-head sales-section-title"><h3>Contacts</h3>${salesBtn('+ Add contact','new-contact',p.id)}</div>${contacts||'<p class="sales-small">Add a contact and record where the email address came from.</p>'}
 <h3 class="sales-section-title">Conversations</h3>${detail.conversations.map(c=>`<div class="sales-row">${salesPill(c.state)} ${salesEsc(c.recipient)} ${salesBtn('Open','conversation',c.id)}</div>`).join('')||'<p class="sales-small">No conversations yet. One open conversation per company prevents duplicate approaches.</p>'}
 ${detail.client_matches.length?`<p class="sales-small">Possible existing Clients: ${detail.client_matches.map(c=>salesEsc(c.name+' ('+(c.code||'no code')+')')).join(', ')}. Link the existing record when converting.</p>`:''}`,
 `${salesBtn('+ Task','task',p.id)}${salesBtn('Create material','generate-material',p.id)}${p.client_id?`<a class="btn-secondary" href="client.html?id=${encodeURIComponent(p.client_id)}">Open Client</a>`:salesBtn('Convert / link Client','convert',p.id)}${salesSubmit('Save company')}`,
 async()=>{await salesCommand('prospect',{...salesForm(),id:p.id,version:p.version});salesClose(true);await salesLoad();salesNotice('Company saved.');});
}
function salesNewProspect(){salesDialog('Add prospect',`<div class="sales-fields">${salesField('Company name','name','','text',false,'required maxlength="200"')}${salesField('Company domain','domain','','text',false,'required placeholder="example.com" maxlength="253"')}${salesField('Country','country')}${salesField('Sector','sector')}${salesField('Why this company fits','fit_note','','textarea',true,'maxlength="4000"')}${salesField('Evidence URL','source_url','','url',true,'maxlength="2000"')}</div>`,salesSubmit('Add prospect'),async()=>{const result=await salesCommand('prospect',salesForm());await salesLoad();await salesOpenProspect(result.id);});}
function salesContact(id){
 const p=SALES.detail.prospect,k=SALES.detail.contacts.find(x=>x.id===id)||{};
 salesDialog(k.id?'Edit contact':'Add contact',`<div class="sales-fields">${salesField('Full name','name',k.name||'','text',false,'maxlength="200"')}${salesField('Role / title','role_title',k.role_title||'','text',false,'maxlength="200"')}${salesField('Email address','email',k.email||'','email',true,'maxlength="254"')}${salesField('LinkedIn profile URL','linkedin_url',k.linkedin_url||'','url',true,'maxlength="2000"')}${salesField('Evidence source','source_url',k.source_url||'','text',true,'maxlength="2000" placeholder="Public source URL or dated contact record"')}${salesField('Outreach basis / relevance','outreach_basis',k.outreach_basis||'','textarea',true,'maxlength="2000" placeholder="Why this person is appropriate to approach, and the basis for contacting them"')}<label class="sales-check sales-field full"><span><input type="checkbox" name="verified" ${k.verified_at?'checked':''}> I checked this email address and the evidence for contacting this person</span></label></div><p class="sales-small">Research suggestions do not count as verified addresses. Verification is required for sending and expires after 90 days.</p>`,salesSubmit('Save contact'),async()=>{const f=salesForm();await salesCommand('contact',{...f,verified:f.verified==='on',id:k.id||null,version:k.version,prospect_id:p.id});await salesLoad();await salesOpenProspect(p.id);});
}
function salesAttachmentInput(){return '<label class="sales-field full"><span>Attachments (optional, up to 3 files / 1 MB total)</span><input type="file" name="files" multiple></label>';}
async function salesReadFiles(existing=[]){
 const input=salesEl('salesDialogForm').elements.files;if(!input?.files.length)return existing;
 if(input.files.length>3||[...input.files].reduce((sum,f)=>sum+f.size,0)>1000000)throw new Error('Choose at most 3 files with a combined size of 1 MB');
 return Promise.all([...input.files].map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Could not read attachment'));reader.onload=()=>resolve({name:file.name,mime:file.type||'application/octet-stream',content:String(reader.result).split(',')[1]});reader.readAsDataURL(file);})));
}
function salesSequence(id,draft){
 const k=SALES.detail.contacts.find(c=>c.id===id),p=SALES.detail.prospect;
 if(!k)throw new Error('Select a contact first');if(!k.email)throw new Error('Add the contact’s email address first');
 const subject=draft?.subject||'';
 salesDialog(`Outreach · ${p.name}`,`<p class="sales-small">To ${salesEsc(k.name)} &lt;${salesEsc(k.email)}&gt; · From and Reply-To Eli Stoyanova &lt;eli.s@retodo-ops.com&gt;</p><div class="sales-fields">${salesField('Shared subject','subject',subject,'text',true,'required maxlength="200"')}${salesField('Initial email scheduled for','due_at',salesLocal(),'datetime-local',true,'required')}</div>
 <fieldset><legend>Initial email</legend>${salesField('Message','initial',draft?.initial||'','textarea',true,'required maxlength="20000" rows="8"')}${salesSignatureControl('initial','include_initial_signature',draft?.initial||'')}</fieldset>
 <fieldset><legend>Follow-up 1 (optional)</legend>${salesField('Business days after the initial send','delay_one',5,'number',false,'min="1" max="60"')}${salesField('Message','followup_one',draft?.followup_one||'','textarea',true,'maxlength="20000"')}${salesSignatureControl('followup_one','include_followup_one_signature',draft?.followup_one||'')}</fieldset>
 <fieldset><legend>Follow-up 2 (optional)</legend>${salesField('Business days after the initial send','delay_two',12,'number',false,'min="1" max="60"')}${salesField('Message','followup_two',draft?.followup_two||'','textarea',true,'maxlength="20000"')}${salesSignatureControl('followup_two','include_followup_two_signature',draft?.followup_two||'')}</fieldset>${salesAttachmentInput()}<p class="sales-small">Attachments go with the initial email. Follow-ups use the same subject and stay in the Gmail thread. Business days are Monday–Friday in Sofia. Each message appears in Batch review.</p>`,salesSubmit('Save for batch review'),async()=>{
  const f=salesForm(),messages=[{subject:f.subject,body:f.initial,include_signature:f.include_initial_signature==='on',delay_days:0,attachments:await salesReadFiles()}];
  if(f.followup_one.trim())messages.push({subject:f.subject,body:f.followup_one,include_signature:f.include_followup_one_signature==='on',delay_days:Number(f.delay_one)});
  if(f.followup_two.trim())messages.push({subject:f.subject,body:f.followup_two,include_signature:f.include_followup_two_signature==='on',delay_days:Number(f.delay_two)});
  await salesCommand('sequence',{contact_id:k.id,due_at:new Date(f.due_at).toISOString(),messages});salesClose(true);SALES.tab='review';await salesLoad({clearSelection:true});salesNotice('Sequence saved. Review and approve its messages before sending.');
 });
}
function salesFindMessage(id){return SALES.data.review.find(m=>m.id===id)||SALES.detail?.messages.find(m=>m.id===id);}
function salesEditMessage(id){
 const m=salesFindMessage(id);if(!m)throw new Error('Refresh the message before editing');
 salesDialog('Edit Sales draft',`<div class="sales-fields">${salesField('Subject','subject',m.subject,'text',true,'required maxlength="200"')}${salesField('Message','body',m.body,'textarea',true,'required rows="10" maxlength="20000"')}<div class="sales-field full">${salesSignatureControl('body','signature_mode',m.body,m)}</div>${m.kind==='followup'?salesField('Business days after initial send','delay_days',m.delay_days,'number',true,'min="1" max="60" required'):salesField('Scheduled for','due_at',salesLocal(m.due_at),'datetime-local',true,'required')}${salesAttachmentInput()}<label class="sales-check full"><input type="checkbox" name="remove_files">Remove existing attachments</label></div><p class="sales-small">${(m.attachments||[]).map(a=>salesEsc(a.name)).join(', ')||'No existing attachments.'} A replacement upload replaces all existing attachments. Saving returns this message to batch review.</p>`,salesSubmit('Save draft'),async()=>{
  const f=salesForm();await salesCommand('message',{id:m.id,version:m.version,subject:f.subject,body:f.body,signature_mode:f.signature_mode,delay_days:f.delay_days?Number(f.delay_days):m.delay_days,due_at:f.due_at?new Date(f.due_at).toISOString():m.due_at,attachments:await salesReadFiles(f.remove_files==='on'?[]:m.attachments)});salesClose(true);await salesLoad({clearSelection:true});salesNotice('Changes saved. The message needs fresh approval.');
 });
}
function salesReviewBatch(){
 const rows=[...SALES.selected.values()];if(!rows.length)throw new Error('Select the drafts you want to review');if(rows.length>50)throw new Error('Review up to 50 messages at once');rows.forEach(m=>SalesSignature.validate(m.signature));
 salesDialog(`Review ${rows.length} messages`,rows.map(m=>`<section class="sales-review-card"><h3>${salesEsc(m.company)} · ${salesEsc(m.kind)}</h3>${salesMessageMeta(m)}<h3>${salesEsc(m.subject)}</h3>${salesMessageContent(m)}${salesFiles(m)}</section>`).join('')+`<label class="sales-check"><input type="checkbox" name="confirmed" required>I approve these recipients, messages, signatures, attachments and timing for sending from Eli’s Sales alias.</label><p class="sales-small">${SALES.data.settings.sending_enabled?'Due messages can send on the next worker run.':'Sending is currently paused. Approved messages will wait until sending is enabled.'}</p>`,salesSubmit(`Approve ${rows.length} messages`),async()=>{
  await salesCommand('approve',{signature_preview_version:1,messages:rows.map(m=>({id:m.id,version:m.version}))});salesClose(true);await salesLoad({clearSelection:true});salesNotice('Batch approved. Each message will still be checked for replies and suppression before sending.');
  if(SALES.data.settings.sending_enabled)try{await salesApi('run');}catch(e){salesNotice(e.message,true);}
 });
}
async function salesOpenConversation(id){
 const detail=await salesRpc('sales_detail_063',{p_id:id});SALES.detail=detail;const c=detail.conversations.find(c=>c.id===id);if(!c)throw new Error('Conversation not found');
 const messages=detail.messages.filter(m=>m.conversation_id===id).sort((a,b)=>a.step-b.step);
 salesDialog(`Conversation · ${detail.prospect.name}`,`<div class="sales-status-line">${salesPill(c.state)}<span>${salesEsc(c.recipient)}</span></div><p class="sales-small">From / Reply-To: Eli Stoyanova &lt;eli.s@retodo-ops.com&gt; · Last mailbox check ${salesDate(c.synced_at)}</p>${c.pause_reason?`<p>${salesEsc(c.pause_reason)}</p>`:''}${c.last_sync_error?`<p class="sales-error">${salesEsc(c.last_sync_error)}</p>`:''}<div class="sales-timeline">${messages.map(m=>`<article class="sales-row"><div class="sales-card-head"><strong>${salesEsc(m.kind==='external'?(m.direction==='inbound'?'Received':'Sent in Gmail'):m.kind)}</strong>${salesPill(m.state,m.state==='received'?'good':m.state==='uncertain'?'warn':'')}</div><p class="sales-small">${m.sent_at?salesDate(m.sent_at):salesEsc(salesTiming(m))}</p><h3>${salesEsc(m.subject)}</h3>${salesMessageContent(m)}${salesFiles(m)}${m.last_error?`<p class="sales-small">${salesEsc(m.last_error)}</p>`:''}${['draft','approved','failed','cancelled'].includes(m.state)?salesBtn('Edit / review','edit-message',m.id):''}${m.state==='uncertain'?salesBtn('Review uncertain delivery','resolve-unsent',m.id):''}</article>`).join('')}</div>`,`${salesBtn('Add task','task',c.prospect_id)}${['paused','replied'].includes(c.state)?salesBtn('Reopen for review','resume',c.id):''}${salesBtn('Pause sequence','pause',c.id)}${salesBtn('Close','close-conversation',c.id)}${salesBtn('Do not contact','suppress',c.recipient)}${c.thread_id&&!['closed','suppressed'].includes(c.state)?salesBtn('Draft reply','reply',c.id,true):''}`,null);
}
function salesReply(id){const c=SALES.detail.conversations.find(c=>c.id===id),initial=SALES.detail.messages.find(m=>m.conversation_id===id&&m.kind==='initial');salesDialog('Draft reply',`<p class="sales-small">To ${salesEsc(c.recipient)} · Reply-To eli.s@retodo-ops.com</p><div class="sales-fields">${salesField('Subject','subject',initial.subject,'text',true,'required maxlength="200"')}${salesField('Message','body','','textarea',true,'required rows="10" maxlength="20000"')}<div class="sales-field full">${salesSignatureControl('body','include_signature')}</div>${salesAttachmentInput()}</div>`,salesSubmit('Save for batch review'),async()=>{const f=salesForm();await salesCommand('reply',{...f,include_signature:f.include_signature==='on',conversation_id:id,attachments:await salesReadFiles()});salesClose(true);SALES.tab='review';await salesLoad({clearSelection:true});});}
function salesSuppress(target=''){salesDialog('Do not contact',`<div class="sales-fields">${salesField('Email address or company domain','target',target,'text',true,'required')}${salesField('Reason','reason','','textarea',true,'required minlength="3" maxlength="500"')}</div><p class="sales-small">Pending messages stop immediately. A message already handed to Gmail cannot be recalled. Removing a suppression requires a separate administrator review.</p>`,salesSubmit('Block outreach'),async()=>{await salesCommand('suppress',salesForm());salesClose(true);await salesLoad({clearSelection:true});salesNotice('Suppression recorded. Pending outreach is stopped.');});}
function salesConvert(){const {prospect:p,client_matches:matches}=SALES.detail;salesDialog('Convert or link Client',`<p>Sales history will stay with ${salesEsc(p.name)}.</p><div class="sales-fields"><label class="sales-field full"><span>Existing Client</span><select name="client_id"><option value="">Create a new Client</option>${matches.map(c=>`<option value="${c.id}">${salesEsc(c.name)} (${salesEsc(c.code)})</option>`).join('')}</select></label>${salesField('New Client code','code','','text',false,'maxlength="12" placeholder="2–12 letters/numbers"')}<label class="sales-field"><span>Type</span><select name="client_type"><option value="LSP">LSP / Agency</option><option value="Direct">Direct client</option></select></label><label class="sales-field"><span>Currency</span><select name="currency"><option>EUR</option><option>USD</option><option>GBP</option><option>NOK</option><option>SEK</option><option>DKK</option></select></label>${salesField('Other existing Client ID (optional)','other_client_id','','text',true,'placeholder="Paste the id from its Client page URL"')}</div>`,salesSubmit('Convert / link'),async()=>{const f=salesForm();const result=await salesCommand('convert',{...f,client_id:f.other_client_id||f.client_id||null,prospect_id:p.id});salesClose(true);await salesLoad();salesNotice('Linked to Client. Sales history is retained.');location.href=`client.html?id=${encodeURIComponent(result.id)}`;});}
function salesTask(prospectId='',contactId=''){
 const contact=SALES.detail?.contacts.find(c=>c.id===contactId);const title=contact?`LinkedIn: contact ${contact.name||'decision-maker'}`:'';
 salesDialog('Add Sales task',`<div class="sales-fields">${salesField('Task','title',title,'text',true,'required maxlength="200"')}${salesField('Due','due_at',salesLocal(),'datetime-local',true,'required')}${salesField('Notes / manual message','notes',contact?.linkedin_url||'','textarea',true,'maxlength="4000"')}${contact?salesLink(contact.linkedin_url,'Open LinkedIn profile'):''}</div><p class="sales-small">This is a reminder inside Sales. LinkedIn messages and connection requests are sent by you.</p>`,salesSubmit('Save task'),async()=>{const f=salesForm();await salesCommand('task',{...f,prospect_id:prospectId||null,due_at:new Date(f.due_at).toISOString()});salesClose(true);await salesLoad();salesNotice('Task saved in Today.');});
}
function salesResearch(){salesDialog('Find prospect clients',`${salesField('Target brief','brief',SALES.data.settings.target_brief,'textarea',true,'required minlength="5" maxlength="4000" rows="8"')}<p class="sales-small">Research adds up to 5 evidence-backed companies and suggested contacts. Existing company names and domains are skipped. Contact emails remain unverified.</p><p>${SALES.service?.estimate?`Up to ${salesMoney(SALES.service.estimate.research)} is reserved first; unused allowance is released after recorded usage.`:salesEsc(SALES.service?.ai_hold||'AI connection must be configured before research can run.')}</p>`,salesSubmit('Start research'),async()=>{await salesQueueAi('research',{brief:salesForm().brief});});}
async function salesQueueAi(kind,extra={}){
 const key=JSON.stringify({kind,...extra});let id=SALES.aiIds.get(key);if(!id){id=crypto.randomUUID();SALES.aiIds.set(key,id);}
 const job=await salesApi('ai',{id,kind,...extra});SALES.aiIds.delete(key);salesClose(true);SALES.tab='today';await salesLoad();salesNotice(job.wake_error||'Task queued. Results will appear in Today when background processing finishes.');
}
function salesAiDialog(kind,prospectId='',contactId=''){
 const p=SALES.detail?.prospect;salesDialog(kind==='draft'?'Generate an outreach draft':'Generate Sales material',`${salesField('Writing brief','brief','','textarea',true,'maxlength="4000" placeholder="Tone, angle or specific points to cover"')}<p class="sales-small">${prospectId?salesEsc('For '+(p?.name||'the selected prospect')):'Uses your approved company facts.'} Generated copy is a draft for your review.</p><p class="sales-small">${SALES.service?.estimate?`Reserve up to ${salesMoney(SALES.service.estimate.writing)}.`:salesEsc(SALES.service?.ai_hold||'AI setup required.')}</p>`,salesSubmit('Generate draft'),async()=>salesQueueAi(kind,{brief:salesForm().brief,prospect_id:prospectId||undefined,contact_id:contactId||undefined}));
}
async function salesShowJob(id){
 const j=SALES.data.jobs.find(j=>j.id===id);if(!j?.result)return;
 const r=j.result;let body='';
 if(j.kind==='research')body=`<p>${Number(r.imported)||0} companies added to Prospects.</p><p class="sales-small">${salesEsc(r.notes)}</p>${(r.prospects||[]).map(p=>`<section class="sales-row"><h3>${salesEsc(p.name)}</h3><p>${salesEsc(p.fit_note)}</p>${salesLink(p.source_url,'Evidence')}</section>`).join('')}<h3>Sources</h3>${(r.sources||[]).map(s=>`<p>${salesLink(s.url,s.title)}</p>`).join('')}`;
 if(j.kind==='draft')body=`<h3>${salesEsc(r.subject)}</h3>${['initial','followup_one','followup_two','linkedin_note'].map(k=>`<h4>${salesEsc(k.replaceAll('_',' '))}</h4><div class="sales-pre">${salesEsc(r[k])}</div>`).join('')}`;
 if(j.kind==='materials')body=`<h3>${salesEsc(r.title)}</h3><div class="sales-pre">${salesEsc(r.content)}</div>`;
 salesDialog('Completed '+j.kind,body,j.kind==='draft'&&j.payload?.contact?.id?salesBtn('Use in sequence','use-draft',j.id,true):salesBtn('Close','close-dialog'),null);
}
function salesMaterial(id){const m=SALES.data.materials.find(m=>m.id===id)||{};salesDialog(m.id?'Edit Sales material':'Write Sales material',`<div class="sales-fields">${salesField('Title','title',m.title||'','text',true,'required maxlength="200"')}${salesField('Content','content',m.content||'','textarea',true,'required rows="13" maxlength="30000" placeholder="Use ## headings for slides, followed by short paragraphs or bullet lines."')}</div><div id="salesMaterialPreview"></div><p class="sales-small">Use ## for slide headings. Long content continues on additional slides so text remains readable. Save before exporting.</p>`,`${salesBtn('Preview slides','preview-material')}${salesSubmit('Save material')}`,async()=>{await salesCommand('material',{...salesForm(),id:m.id||null,version:m.version});salesClose(true);SALES.tab='materials';await salesLoad();});}

async function salesAction(action,id){
 switch(action){
 case 'toggle-menu':document.body.classList.toggle('sales-menu-open');return;
 case 'new-prospect':return salesNewProspect();case 'prospect':return salesOpenProspect(id);case 'new-contact':return salesContact();case 'contact':return salesContact(id);
 case 'sequence':return salesSequence(id);case 'edit-message':return salesEditMessage(id);case 'review-batch':return salesReviewBatch();case 'conversation':return salesOpenConversation(id);case 'reply':return salesReply(id);
 case 'settings':return salesSetTab('settings');case 'close-dialog':return salesClose();case 'suppress':return salesSuppress(id);case 'convert':return salesConvert();
 case 'task':return salesTask(id);case 'linkedin-task':return salesTask(SALES.detail.prospect.id,id);case 'task-done':await salesCommand('task',{id,done:true});return salesLoad();
 case 'resolve-unsent':salesDialog('Review uncertain delivery',`<p>A missing result does not prove the email failed. Check Gmail Sent, including a search for the Message-ID below, before recording a decision. A mistaken decision can cause duplicate outreach.</p><div class="sales-pre">${salesEsc(salesFindMessage(id)?.rfc_id)}</div>${salesField('What you checked in Gmail','reason','','textarea',true,'required minlength="20" maxlength="500"')}<label class="sales-check"><input type="checkbox" name="confirmed" required>I confirmed this message was not sent. I understand it will need editing and fresh approval before any retry.</label>`,salesSubmit('Record confirmed not sent'),async()=>{await salesCommand('resolve_unsent',{id,reason:salesForm().reason,confirmed:true});salesClose(true);await salesLoad();salesNotice('Recorded. Edit and approve the message to retry.');});return;
 case 'resume':await salesCommand('resume',{conversation_id:id});salesClose(true);await salesLoad();salesNotice('Reopened for review. Cancelled messages stay cancelled until you edit and reapprove them.');return;
 case 'pause':case 'close-conversation':await salesCommand(action==='pause'?'pause':'close',{conversation_id:id,reason:action==='pause'?'Paused by administrator':'Closed by administrator'});salesClose(true);return salesLoad({clearSelection:true});
 case 'research':return salesResearch();case 'draft':return salesAiDialog('draft',SALES.detail.prospect.id,id);case 'generate-material':return salesAiDialog('materials',id);case 'job':return salesShowJob(id);
 case 'use-draft':{const j=SALES.data.jobs.find(j=>j.id===id);SALES.detail=await salesRpc('sales_detail_063',{p_id:j.payload.prospect.id});return salesSequence(j.payload.contact.id,j.result);}
 case 'new-material':return salesMaterial();case 'material':return salesMaterial(id);case 'preview-material':{const f=salesForm();salesEl('salesMaterialPreview').innerHTML=window.SalesMaterials.preview(f);return;}
 case 'pptx':return window.SalesMaterials.powerpoint(SALES.data.materials.find(m=>m.id===id));case 'material-text':return window.SalesMaterials.text(SALES.data.materials.find(m=>m.id===id));
 case 'material-print':return window.SalesMaterials.print(SALES.data.materials.find(m=>m.id===id));
 case 'attachment':{const [messageId,index]=id.split(':'),m=salesFindMessage(messageId)||SALES.selected.get(messageId),a=m?.attachments?.[Number(index)];if(!a)throw new Error('Attachment is unavailable');const bytes=Uint8Array.from(atob(a.content),c=>c.charCodeAt(0));window.SalesMaterials.download(new Blob([bytes],{type:a.mime}),a.name);return;}
 case 'search':SALES.query=salesEl('salesSearch').value.trim();SALES.offset=0;return salesLoad({clearSelection:true});case 'clear-search':SALES.query='';SALES.offset=0;return salesLoad({clearSelection:true});
 case 'previous':SALES.offset=Math.max(0,SALES.offset-50);return salesLoad();case 'next':if(SALES.offset+50<SALES.data.prospect_count){SALES.offset+=50;return salesLoad();}return;
 case 'refresh':return salesLoad({clearSelection:true});case 'run':await salesApi('run');salesNotice('Background check started. Refresh shortly to see the result.');return;
 case 'check-mailbox':{const r=await salesApi('check_mailbox');salesNotice(`Mailbox check passed: ${r.account}. Sales sender: ${r.alias}.`);return salesLoad();}
 case 'status':SALES.service=await salesApi('status');salesRender();return;
 }
}

document.addEventListener('click',async e=>{
 const tab=e.target.closest('[data-tab]');if(tab){salesSetTab(tab.dataset.tab);return;}
 const button=e.target.closest('[data-action]');if(!button||button.disabled)return;
 if(SALES.tab==='settings'&&SALES.settingsDirty&&!salesEl('salesDialog').open&&!['check-mailbox','status','toggle-menu','suppress'].includes(button.dataset.action)){salesNotice('Save your Sales settings before starting another action.',true);return;}
 const navigation=['new-contact','contact','sequence','draft','linkedin-task','convert','generate-material','reply','edit-message','task','use-draft'];
 if(SALES.dirty&&salesEl('salesDialog').open&&navigation.includes(button.dataset.action)&&!confirm('Discard unsaved changes and continue?'))return;
 button.disabled=true;
 try{await salesAction(button.dataset.action,button.dataset.id||'');}catch(error){if(salesEl('salesDialog').open)salesEl('salesDialogError').textContent=error.message;else salesNotice(error.message,true);}finally{button.disabled=false;}
});
document.addEventListener('change',e=>{
 if(e.target.matches('[data-select]')){const id=e.target.dataset.select;if(e.target.checked){if(SALES.selected.size>=50){e.target.checked=false;salesNotice('Select at most 50 messages per batch.',true);return;}SALES.selected.set(id,SALES.data.review.find(m=>m.id===id));}else SALES.selected.delete(id);salesRender();}
 if(e.target.id==='salesSelectAll'){SALES.selected.clear();if(e.target.checked)SALES.data.review.slice(0,50).forEach(m=>SALES.selected.set(m.id,m));salesRender();}
});
document.addEventListener('input',e=>{if(e.target.closest('#salesDialogForm'))SALES.dirty=true;if(e.target.closest('#salesSettingsForm'))SALES.settingsDirty=true;if(e.target.closest('#salesSettingsForm,#salesDialogForm'))salesRefreshSignaturePreviews();});
document.addEventListener('change',e=>{if(e.target.closest('[data-message-preview],.sales-signature-choice,#salesSignatureSettings')){if(e.target.closest('#salesDialogForm'))SALES.dirty=true;if(e.target.closest('#salesSettingsForm'))SALES.settingsDirty=true;salesRefreshSignaturePreviews();}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='salesSearch'){e.preventDefault();salesAction('search').catch(err=>salesNotice(err.message,true));}});
salesEl('salesDialog').addEventListener('cancel',e=>{e.preventDefault();salesClose();});
document.addEventListener('submit',async e=>{
 if(!['salesDialogForm','salesSettingsForm'].includes(e.target.id))return;e.preventDefault();
 const button=e.submitter;if(button?.disabled)return;if(button)button.disabled=true;
 try{
  if(e.target.id==='salesDialogForm'&&SALES.dialogSubmit)await SALES.dialogSubmit();
  if(e.target.id==='salesSettingsForm'){
   const f=Object.fromEntries(new FormData(e.target));const signatureFields=SALES.data.settings.email_signature?{email_signature:salesSignatureFromForm(e.target),signature_enabled:f.signature_enabled==='on'}:{};if(signatureFields.email_signature)SalesSignature.validate(signatureFields.email_signature);await salesCommand('settings',{...f,...signatureFields,sending_enabled:f.sending_enabled==='on',research_enabled:f.research_enabled==='on'});SALES.settingsDirty=false;SALES.dirty=false;await salesLoad();salesNotice('Sales settings saved.');
  }
 }catch(error){if(e.target.id==='salesDialogForm')salesEl('salesDialogError').textContent=error.message;else salesNotice(error.message,true);}finally{if(button)button.disabled=false;}
});
window.addEventListener('beforeunload',e=>{if(SALES.dirty||SALES.settingsDirty){e.preventDefault();e.returnValue='';}});
(async()=>{
 const user=await requireAuth();if(!user)return;
 if(await currentAppRole()!=='admin'){document.querySelectorAll('.sales-actions,.sales-tabs,.sales-identity').forEach(e=>e.hidden=true);salesEl('salesView').innerHTML='<div class="sales-empty">Sales is available to administrators during the pilot.</div>';return;}
 await salesLoad();try{SALES.service=await salesApi('status');if(SALES.tab==='settings')salesRender();}catch(e){SALES.service={ai_hold:e.message};}
 const id=new URLSearchParams(location.search).get('id');if(id)try{await salesOpenProspect(id);}catch(e){salesNotice(e.message,true);}
 setInterval(()=>{if(!document.hidden&&!salesEl('salesDialog').open&&['today','conversations'].includes(SALES.tab))salesLoad({quiet:true});},20000);
})().catch(e=>salesNotice(e.message,true));
